// Isi dari file bankSoal.js

const bankSoal = [
    // --- Pengetahuan Umum Dunia ---
    { soal: "Apa nama mata uang negara Korea Selatan?", jawaban: "Won", poin: 30 },
    { soal: "Menara Eiffel terletak di kota apa?", jawaban: "Paris", poin: 20 },
    { soal: "Negara mana yang memiliki julukan Negeri Matahari Terbit?", jawaban: "Jepang", poin: 20 },
    { soal: "Apa nama samudera terluas di dunia?", jawaban: "Pasifik", poin: 30 },
    { soal: "Benua terkecil di dunia adalah...", jawaban: "Australia", poin: 30 },
    { soal: "Pusat peredaran tata surya kita adalah...", jawaban: "Matahari", poin: 20 },
    { soal: "Gunung tertinggi di dunia adalah Gunung...", jawaban: "Everest", poin: 20 },
    { soal: "Negara manakah yang memenangkan Piala Dunia FIFA terbanyak?", jawaban: "Brasil", poin: 40 },
    { soal: "Siapakah pelukis lukisan Monalisa?", jawaban: "Leonardo da Vinci", poin: 40 },
    { soal: "Apa ibu kota dari negara Australia?", jawaban: "Canberra", poin: 50 },
    { soal: "Organisasi kesehatan dunia di bawah PBB disebut...", jawaban: "WHO", poin: 30 },
    { soal: "Patung Liberty merupakan hadiah dari negara mana untuk Amerika Serikat?", jawaban: "Prancis", poin: 50 },
    { soal: "Apa nama benua yang tidak berpenghuni tetap?", jawaban: "Antartika", poin: 30 },
    { soal: "Penemu benua Amerika adalah...", jawaban: "Christopher Columbus", poin: 40 },
    { soal: "Berapa jumlah warna pada pelangi?", jawaban: "7", poin: 20 },
    { soal: "Arah matahari terbit adalah dari...", jawaban: "Timur", poin: 10 },
    { soal: "Sistem pemerintahan dimana rakyat memegang kekuasaan tertinggi disebut...", jawaban: "Demokrasi", poin: 40 },
    { soal: "Apa nama senjata tradisional suku Aborigin?", jawaban: "Bumerang", poin: 30 },
    { soal: "Batu permata terkeras di dunia adalah...", jawaban: "Berlian", poin: 40 },
    { soal: "Pakaian tradisional wanita Jepang adalah...", jawaban: "Kimono", poin: 20 },

    // --- Pengetahuan Umum & Sejarah Indonesia ---
    { soal: "Siapakah presiden ketiga Republik Indonesia?", jawaban: "B.J. Habibie", poin: 30 },
    { soal: "Candi Borobudur merupakan candi bercorak agama...", jawaban: "Buddha", poin: 20 },
    { soal: "Tanggal berapakah Hari Pendidikan Nasional diperingati?", jawaban: "2 Mei", poin: 40 },
    { soal: "Siapakah pahlawan yang dijuluki Bapak Pendidikan Nasional?", jawaban: "Ki Hajar Dewantara", poin: 30 },
    { soal: "Sumpah Pemuda diikrarkan pada tahun berapa?", jawaban: "1928", poin: 50 },
    { soal: "Kerajaan Hindu tertua di Indonesia adalah...", jawaban: "Kutai", poin: 40 },
    { soal: "Apa nama selat yang memisahkan Pulau Jawa dan Sumatera?", jawaban: "Selat Sunda", poin: 30 },
    { soal: "Tari Kecak berasal dari daerah mana?", jawaban: "Bali", poin: 20 },
    { soal: "Ibu kota provinsi Jawa Tengah adalah...", jawaban: "Semarang", poin: 20 },
    { soal: "Siapakah penjahit bendera Sang Saka Merah Putih?", jawaban: "Fatmawati", poin: 30 },
    { soal: "Hewan endemik yang hanya ada di Pulau Komodo adalah...", jawaban: "Komodo", poin: 20 },
    { soal: "Danau terbesar di Indonesia adalah Danau...", jawaban: "Toba", poin: 20 },
    { soal: "Senjata tradisional keris diakui UNESCO berasal dari negara...", jawaban: "Indonesia", poin: 20 },
    { soal: "Semboyan Bhinneka Tunggal Ika diambil dari kitab...", jawaban: "Sutasoma", poin: 50 },
    { soal: "Provinsi paling timur di Indonesia adalah...", jawaban: "Papua", poin: 20 },
    { soal: "Pahlawan dari Maluku yang memimpin perlawanan di Saparua adalah...", jawaban: "Pattimura", poin: 40 },
    { soal: "Pencipta lagu Mengheningkan Cipta adalah...", jawaban: "Truno Prawit", poin: 50 },
    { soal: "Gunung tertinggi di Pulau Jawa adalah...", jawaban: "Semeru", poin: 40 },
    { soal: "Lagu daerah 'Ampar-Ampar Pisang' berasal dari provinsi...", jawaban: "Kalimantan Selatan", poin: 40 },
    { soal: "Kesenian Reog berasal dari kota...", jawaban: "Ponorogo", poin: 30 },

    // --- Sains & Biologi ---
    { soal: "Gas apa yang kita hirup saat bernapas?", jawaban: "Oksigen", poin: 20 },
    { soal: "Proses tumbuhan membuat makanannya sendiri disebut...", jawaban: "Fotosintesis", poin: 30 },
    { soal: "Pusat dari tata surya adalah...", jawaban: "Matahari", poin: 10 },
    { soal: "Satuan tegangan listrik adalah...", jawaban: "Volt", poin: 30 },
    { soal: "Hewan mamalia laut terbesar adalah...", jawaban: "Paus Biru", poin: 30 },
    { soal: "Benda langit yang mengelilingi planet disebut...", jawaban: "Satelit", poin: 30 },
    { soal: "Alat untuk mengukur suhu adalah...", jawaban: "Termometer", poin: 20 },
    { soal: "Bahan penyusun utama tulang manusia adalah...", jawaban: "Kalsium", poin: 30 },
    { soal: "Cabang ilmu yang mempelajari tentang tumbuhan adalah...", jawaban: "Botani", poin: 40 },
    { soal: "Hewan pemakan daging disebut...", jawaban: "Karnivora", poin: 20 },
    { soal: "Warna hijau pada daun disebabkan oleh adanya...", jawaban: "Klorofil", poin: 30 },
    { soal: "Perubahan wujud dari cair menjadi gas disebut...", jawaban: "Menguap", poin: 20 },
    { soal: "Berapa jumlah titik pada dua buah dadu?", jawaban: "42", poin: 50 },
    { soal: "Golongan darah yang disebut sebagai donor universal adalah...", jawaban: "O", poin: 40 },
    { soal: "Zat yang memberi warna merah pada darah adalah...", jawaban: "Hemoglobin", poin: 40 },
    { soal: "Tulang terkecil pada tubuh manusia terdapat di bagian...", jawaban: "Telinga", poin: 50 },
    { soal: "Gaya yang menarik semua benda ke pusat bumi disebut gaya...", jawaban: "Gravitasi", poin: 20 },
    { soal: "Burung tercepat di dunia saat menukik adalah burung...", jawaban: "Peregrine Falcon", poin: 60 },
    { soal: "Sel darah yang berfungsi melawan infeksi adalah sel darah...", jawaban: "Putih", poin: 30 },
    { soal: "Air mendidih pada suhu berapa derajat Celcius?", jawaban: "100", poin: 20 },

    // --- Teknologi & Programming ---
    { soal: "Framework PHP yang menggunakan arsitektur MVC dan sangat populer saat ini adalah...", jawaban: "Laravel", poin: 40 },
    { soal: "Perangkat keras komputer yang berfungsi sebagai otak utama adalah...", jawaban: "CPU", poin: 30 },
    { soal: "Apa kepanjangan dari IoT?", jawaban: "Internet of Things", poin: 40 },
    { soal: "Microcontroller yang sering digunakan untuk proyek IoT dan memiliki modul WiFi bawaan (seperti ESP8266) sering disebut board...", jawaban: "NodeMCU", poin: 50 },
    { soal: "Sistem operasi open-source berbasis Linux yang sangat populer untuk server dan berlogo penguin adalah...", jawaban: "Ubuntu", poin: 40 },
    { soal: "Bahasa markup yang digunakan untuk membuat struktur halaman web adalah...", jawaban: "HTML", poin: 20 },
    { soal: "Simbol '#' pada URL biasa disebut dengan istilah...", jawaban: "Hashtag", poin: 30 },
    { soal: "Apa nama perintah pada Linux Ubuntu untuk mendapatkan hak akses administrator?", jawaban: "Sudo", poin: 40 },
    { soal: "Jenis kabel yang mentransmisikan data menggunakan cahaya adalah...", jawaban: "Fiber Optik", poin: 40 },
    { soal: "Komponen yang digunakan untuk membaca kartu identitas berbasis gelombang radio pada proyek mikrokontroler adalah modul...", jawaban: "RFID", poin: 50 },
    { soal: "Jaringan pribadi maya yang sering digunakan untuk mengamankan koneksi internet disebut...", jawaban: "VPN", poin: 30 },
    { soal: "Bahasa pemrograman yang digunakan untuk memberikan gaya atau tampilan pada halaman web adalah...", jawaban: "CSS", poin: 30 },
    { soal: "Singkatan dari WWW pada alamat website adalah...", jawaban: "World Wide Web", poin: 20 },
    { soal: "Database relasional yang sangat populer dan berlogo lumba-lumba adalah...", jawaban: "MySQL", poin: 30 },
    { soal: "Orang yang membuat program komputer disebut...", jawaban: "Programmer", poin: 20 },
    { soal: "Apa nama firewall bawaan default pada Ubuntu yang sangat mudah dikonfigurasi?", jawaban: "UFW", poin: 60 },
    { soal: "Ekstensi file untuk dokumen Portable Document Format adalah...", jawaban: "PDF", poin: 20 },
    { soal: "Perangkat lunak yang berfungsi untuk menjelajahi internet disebut...", jawaban: "Browser", poin: 20 },
    { soal: "Layanan penyedia sertifikat SSL gratis yang sangat populer untuk web server adalah...", jawaban: "Let's Encrypt", poin: 50 },
    { soal: "Aplikasi pengirim pesan instan berlogo gagang telepon warna hijau adalah...", jawaban: "WhatsApp", poin: 10 },

    // --- Agama & Kebudayaan Islami ---
    { soal: "Nabi yang memiliki mukjizat bisa membelah lautan adalah Nabi...", jawaban: "Musa", poin: 30 },
    { soal: "Surah pertama dalam Al-Quran adalah Surah...", jawaban: "Al-Fatihah", poin: 20 },
    { soal: "Malaikat yang bertugas membagi rezeki adalah Malaikat...", jawaban: "Mikail", poin: 30 },
    { soal: "Kota suci tempat umat Islam melaksanakan ibadah Haji adalah...", jawaban: "Mekkah", poin: 20 },
    { soal: "Bulan dimana umat Islam diwajibkan berpuasa sebulan penuh adalah bulan...", jawaban: "Ramadhan", poin: 20 },
    { soal: "Nabi yang mendapat julukan Bapak Para Nabi adalah Nabi...", jawaban: "Ibrahim", poin: 40 },
    { soal: "Kiblat umat Islam saat melaksanakan salat adalah...", jawaban: "Ka'bah", poin: 20 },
    { soal: "Hari raya umat Islam setelah sebulan berpuasa disebut Hari Raya...", jawaban: "Idul Fitri", poin: 20 },
    { soal: "Malaikat yang bertugas meniup sangkakala pada hari kiamat adalah Malaikat...", jawaban: "Israfil", poin: 40 },
    { soal: "Tempat ibadah umat Islam adalah...", jawaban: "Masjid", poin: 10 },
    { soal: "Kitab suci yang diturunkan kepada Nabi Daud adalah kitab...", jawaban: "Zabur", poin: 30 },
    { soal: "Salat wajib yang dilakukan pada waktu fajar/pagi hari adalah salat...", jawaban: "Subuh", poin: 20 },
    { soal: "Perjalanan malam Nabi Muhammad dari Masjidil Haram ke Masjidil Aqsa disebut...", jawaban: "Isra", poin: 40 },
    { soal: "Istri pertama Nabi Muhammad SAW bernama...", jawaban: "Khadijah", poin: 30 },
    { soal: "Surah terpanjang dalam Al-Quran adalah Surah...", jawaban: "Al-Baqarah", poin: 40 },
    { soal: "Hukum membaca Al-Quran bagi umat Islam adalah...", jawaban: "Sunnah", poin: 30 }, // Bisa diperdebatkan, tapi aman untuk kuis umum
    { soal: "Pintu surga yang diperuntukkan bagi orang-orang yang berpuasa bernama pintu...", jawaban: "Ar-Rayyan", poin: 50 },
    { soal: "Nama raja yang mencoba menghancurkan Ka'bah dengan pasukan gajah adalah Raja...", jawaban: "Abrahah", poin: 40 },
    { soal: "Malaikat yang mencatat amal baik manusia adalah Malaikat...", jawaban: "Rakib", poin: 30 },
    { soal: "Salat sunnah yang dilakukan pada malam bulan Ramadhan disebut salat...", jawaban: "Tarawih", poin: 20 },

    // --- Tebak-tebakan Logika (Bikin Mikir) ---
    { soal: "Apa yang selalu datang tapi tidak pernah tiba?", jawaban: "Besok", poin: 60 },
    { soal: "Jika kamu sedang balapan lari dan menyalip orang di posisi kedua, sekarang kamu di posisi berapa?", jawaban: "Dua", poin: 50 },
    { soal: "Bulan apa yang memiliki 28 hari?", jawaban: "Semua bulan", poin: 50 },
    { soal: "Semakin banyak kamu mengambilnya, semakin banyak yang kamu tinggalkan. Apakah itu?", jawaban: "Jejak langkah", poin: 60 },
    { soal: "Benda apa yang kalau dipegang malah rusak?", jawaban: "Janji", poin: 60 },
    { soal: "Apa yang tidak punya awal, tengah, atau akhir?", jawaban: "Lingkaran", poin: 50 },
    { soal: "Berapa banyak huruf dalam 'Abjad'?", jawaban: "5", poin: 40 }, // A-B-J-A-D
    { soal: "Ayah Mary punya 5 anak: Nana, Nene, Nini, Nono. Siapa nama anak kelima?", jawaban: "Mary", poin: 40 },
    { soal: "Apa yang punya mata banyak tapi tidak bisa melihat?", jawaban: "Nanas", poin: 50 },
    { soal: "Kalau jatuh tidak bisa bangun lagi, kalau tidak jatuh malah terus jalan. Apakah itu?", jawaban: "Air terjun", poin: 60 },
    { soal: "Aku punya ruang tapi tidak punya pintu. Aku punya tombol tapi tidak bisa ditekan (secara fisik). Apakah aku?", jawaban: "Keyboard", poin: 60 },
    { soal: "Aku bisa berjalan tanpa kaki, aku bisa menangis tanpa mata. Ke mana pun aku pergi, kegelapan mengikutiku. Apakah aku?", jawaban: "Awan", poin: 70 },
    { soal: "Benda apa yang selalu diinjak-injak orang tapi tidak pernah marah?", jawaban: "Lantai", poin: 30 },
    { soal: "Apa yang bisa dipecahkan tanpa dipegang?", jawaban: "Janji", poin: 50 },
    { soal: "Punya banyak gigi tapi tidak bisa menggigit?", jawaban: "Sisir", poin: 40 },
    { soal: "Semakin basah, semakin bisa mengeringkan benda lain. Apakah aku?", jawaban: "Handuk", poin: 50 },
    { soal: "Dibeli mahal-mahal, lalu dirobek. Apakah itu?", jawaban: "Tiket", poin: 50 },
    { soal: "Punya empat kaki saat pagi, dua kaki saat siang, dan tiga kaki saat malam. Apakah itu?", jawaban: "Manusia", poin: 80 }, // Teka-teki Sphinx
    { soal: "Aku ringan seperti bulu, tapi manusia paling kuat pun tidak bisa menahanku lebih dari 5 menit. Apakah aku?", jawaban: "Napas", poin: 70 },
    { soal: "Benda apa yang ukurannya membesar saat basah dan mengecil saat kering?", jawaban: "Spons", poin: 40 },

    // --- Tebak-tebakan Lucu / Receh (Bikin Kesel) ---
    { soal: "Sapi apa yang larinya cepet?", jawaban: "Sapida motor", poin: 50 },
    { soal: "Gajah terbang dengan apa?", jawaban: "Dengan susah payah", poin: 60 },
    { soal: "Kenapa pohon mangga di depan rumah harus ditebang?", jawaban: "Kalau dicabut berat", poin: 50 },
    { soal: "Penyanyi luar negeri yang suka sepedaan?", jawaban: "Selena Gowes", poin: 50 },
    { soal: "Burung apa yang bisa berdiri, bisa tiduran, tapi nggak bisa terbang?", jawaban: "Burung puyuh goreng", poin: 60 },
    { soal: "Kenapa Superman bajunya ada huruf S?", jawaban: "Kalau M atau L kegedean", poin: 50 },
    { soal: "Pintu apa yang didorong oleh 10 orang tetap nggak bisa terbuka?", jawaban: "Pintu geser", poin: 50 },
    { soal: "Benda apa yang kalau dilihat kotak, tapi kalau dipegang bulat?", jawaban: "Tahu bulat digoreng dadakan", poin: 60 },
    { soal: "Kebo apa yang bikin lelah?", jawaban: "Kebogor jalan kaki", poin: 50 },
    { soal: "Hewan apa yang warnanya hitam, putih, dan merah?", jawaban: "Zebra masuk angin habis dikerok", poin: 70 },
    { soal: "Kenapa ayam merem kalau berkokok?", jawaban: "Karena udah hafal liriknya", poin: 60 },
    { soal: "Mobil apa yang bikin kaget?", jawaban: "Mobilang sayang tapi udah ada yang punya", poin: 70 },
    { soal: "Ikan apa yang matanya banyak sekali?", jawaban: "Ikan teri sekilo", poin: 50 },
    { soal: "Mandi apa yang nggak bikin basah?", jawaban: "MANDIrikan rumah tangga bersamamu", poin: 60 },
    { soal: "Buah apa yang selalu bikin was-was?", jawaban: "Buahaya", poin: 40 },
    { soal: "Orang apa yang kalau dipukul nggak sakit?", jawaban: "Orang nggak kena", poin: 50 },
    { soal: "Telor apa yang ditakuti semua orang?", jawaban: "Telor asin... maksudnya Teroris", poin: 60 },
    { soal: "Bebek apa yang jalannya selalu muter ke kiri terus?", jawaban: "Bebek dikunci stang", poin: 70 },
    { soal: "Kunci apa yang bisa bikin orang tersenyum?", jawaban: "Kunci-kupan (Kecupan)", poin: 60 },
    { soal: "Daun apa yang tidak pernah gugur?", jawaban: "Daun telinga", poin: 40 },

    // --- Kuliner & Makanan ---
    { soal: "Makanan khas Palembang yang terbuat dari ikan dan sagu adalah...", jawaban: "Pempek", poin: 20 },
    { soal: "Rendang adalah makanan tradisional yang berasal dari daerah...", jawaban: "Padang", poin: 20 },
    { soal: "Bahan utama pembuatan tahu dan tempe adalah kacang...", jawaban: "Kedelai", poin: 20 },
    { soal: "Makanan khas Italia yang berbentuk bundar pipih dan ditaburi keju serta saus tomat adalah...", jawaban: "Pizza", poin: 20 },
    { soal: "Minuman boba atau bubble tea pertama kali berasal dari negara...", jawaban: "Taiwan", poin: 40 },
    { soal: "Sup khas Jepang yang berwarna keruh dan terbuat dari fermentasi kedelai adalah sup...", jawaban: "Miso", poin: 40 },
    { soal: "Sate lilit adalah makanan khas dari pulau...", jawaban: "Bali", poin: 30 },
    { soal: "Makanan ringan khas Bandung yang terbuat dari aci digoreng disebut...", jawaban: "Cireng", poin: 30 },
    { soal: "Sayuran yang identik sebagai makanan kesukaan kelinci dan tokoh kartun Bugs Bunny adalah...", jawaban: "Wortel", poin: 10 },
    { soal: "Gudeg adalah sayur nangka muda manis yang merupakan makanan khas dari kota...", jawaban: "Yogyakarta", poin: 20 },
    { soal: "Makanan mie pedas asal Korea Selatan yang sangat populer disebut...", jawaban: "Ramyun", poin: 30 },
    { soal: "Onde-onde biasanya berisi tumbukan kacang...", jawaban: "Hijau", poin: 30 },
    { soal: "Bumbu dapur yang membuat masakan menjadi warna kuning adalah...", jawaban: "Kunyit", poin: 20 },
    { soal: "Kerak telor adalah makanan khas dari daerah...", jawaban: "Jakarta", poin: 30 },
    { soal: "Daging yang diiris tipis, ditusuk, lalu dibakar di atas arang disebut...", jawaban: "Sate", poin: 10 },
    { soal: "Keju, yogurt, dan mentega merupakan produk olahan dari...", jawaban: "Susu", poin: 20 },
    { soal: "Sambal khas Manado yang sangat pedas bernama sambal...", jawaban: "Dabu-dabu", poin: 50 },
    { soal: "Bahan dasar pembuatan kecap manis adalah...", jawaban: "Kedelai hitam", poin: 40 },
    { soal: "Buah yang dijuluki 'Raja Buah' karena aromanya yang sangat kuat adalah...", jawaban: "Durian", poin: 20 },
    { soal: "Papeda adalah makanan pokok khas Indonesia bagian timur yang terbuat dari...", jawaban: "Sagu", poin: 30 },

    // --- Olahraga & Permainan ---
    { soal: "Induk organisasi sepak bola dunia adalah...", jawaban: "FIFA", poin: 20 },
    { soal: "Permainan bulu tangkis biasanya dimainkan hingga mencapai skor...", jawaban: "21", poin: 30 },
    { soal: "Jumlah pemain dalam satu tim bola basket adalah...", jawaban: "5", poin: 20 },
    { soal: "Seni bela diri asli Indonesia adalah...", jawaban: "Pencak Silat", poin: 20 },
    { soal: "Berapa jumlah kotak (hitam dan putih) pada papan catur?", jawaban: "64", poin: 50 },
    { soal: "Olahraga lari jarak jauh dengan jarak sekitar 42 km disebut...", jawaban: "Maraton", poin: 40 },
    { soal: "Dalam sepak bola, pelanggaran di area kotak penalti akan menghasilkan tendangan...", jawaban: "Penalti", poin: 10 },
    { soal: "Pukulan menukik tajam dan keras dalam bola voli disebut...", jawaban: "Smash", poin: 30 },
    { soal: "Negara yang menciptakan olahraga tenis meja (pingpong) adalah...", jawaban: "Inggris", poin: 50 },
    { soal: "Warna sabuk tertinggi dalam olahraga karate adalah...", jawaban: "Hitam", poin: 20 },
    { soal: "Gaya renang yang gerakannya menyerupai katak berenang disebut gaya...", jawaban: "Dada", poin: 30 },
    { soal: "Berapa lama waktu normal dalam satu babak pertandingan sepak bola? (dalam menit)", jawaban: "45", poin: 20 },
    { soal: "Pemain sepak bola yang bertugas menjaga gawang disebut...", jawaban: "Kiper", poin: 10 },
    { soal: "Turnamen bulu tangkis beregu putra tingkat dunia memperebutkan piala...", jawaban: "Thomas", poin: 40 },
    { soal: "Alat pemukul dalam permainan bisbol disebut...", jawaban: "Tongkat", poin: 20 },
    { soal: "Istilah 'Strike' dalam olahraga bowling berarti menjatuhkan berapa pin pada lemparan pertama?", jawaban: "10", poin: 30 },
    { soal: "Lintasan balap mobil F1 di Indonesia yang berada di Jakarta Utara adalah sirkuit...", jawaban: "Ancol", poin: 40 }, // Sirkuit Formula E
    { soal: "Michael Jordan adalah legenda olahraga...", jawaban: "Bola Basket", poin: 20 },
    { soal: "Senjata yang digunakan dalam olahraga anggar dinamakan...", jawaban: "Pedang", poin: 20 },
    { soal: "Permainan tradisional memukul bola dengan kayu dan berlari ke tiang hinggap disebut...", jawaban: "Kasti", poin: 30 },

    // --- Pop Culture, Film, Seni & Hiburan ---
    { soal: "Siapa nama tokoh utama berwujud kucing mesin dari masa depan?", jawaban: "Doraemon", poin: 20 },
    { soal: "Grup band asal Inggris yang menyanyikan lagu 'Bohemian Rhapsody' adalah...", jawaban: "Queen", poin: 40 },
    { soal: "Di film Harry Potter, asrama yang memiliki lambang singa adalah...", jawaban: "Gryffindor", poin: 30 },
    { soal: "Siapa nama asli superhero Spiderman?", jawaban: "Peter Parker", poin: 20 },
    { soal: "Anime tentang petualangan mencari harta karun peninggalan Raja Bajak Laut bernama...", jawaban: "One Piece", poin: 20 },
    { soal: "Sutradara Indonesia yang menyutradarai film 'Laskar Pelangi' adalah...", jawaban: "Riri Riza", poin: 50 },
    { soal: "Warna yang melambangkan keberanian pada bendera Indonesia adalah...", jawaban: "Merah", poin: 10 },
    { soal: "Tokoh monster hijau besar yang suka marah di komik Marvel bernama...", jawaban: "Hulk", poin: 20 },
    { soal: "Berapa jumlah senar pada gitar akustik standar?", jawaban: "6", poin: 20 },
    { soal: "Film animasi buatan Disney tentang boneka salju yang bisa bicara bernama Olaf berjudul...", jawaban: "Frozen", poin: 20 },
    { soal: "Tarian khas daerah yang dilakukan secara massal dari Aceh dan diakui UNESCO adalah tari...", jawaban: "Saman", poin: 30 },
    { soal: "Siapa penyanyi Indonesia yang mendapat julukan 'Bapak Patah Hati Nasional' (Godfather of Broken Heart)?", jawaban: "Didi Kempot", poin: 30 },
    { soal: "Game kotak-kotak di mana pemain bisa membangun apa saja disebut...", jawaban: "Minecraft", poin: 20 },
    { soal: "Dalam serial SpongeBob SquarePants, siapa nama bos dari SpongeBob?", jawaban: "Mr. Krabs", poin: 20 },
    { soal: "Instrumen musik yang cara memainkannya dengan digesek adalah...", jawaban: "Biola", poin: 20 },
    { soal: "Karakter game yang identik dengan memakan titik-titik kuning dan dikejar hantu warna-warni adalah...", jawaban: "Pac-Man", poin: 30 },
    { soal: "Boyband asal Korea Selatan yang memiliki lagu hit 'Dynamite' adalah...", jawaban: "BTS", poin: 20 },
    { soal: "Di negara fiksi manakah tokoh Black Panther berasal?", jawaban: "Wakanda", poin: 30 },
    { soal: "Siapakah aktor pemeran karakter Iron Man di Marvel Cinematic Universe?", jawaban: "Robert Downey Jr", poin: 40 },
    { soal: "Seni melipat kertas yang berasal dari Jepang disebut...", jawaban: "Origami", poin: 30 },
    { soal: "Sebutan untuk murid yang menimba ilmu agama di pondok adalah...", jawaban: "Santri", poin: 20 },
    { soal: "Kamar tidur khas santri di pesantren salaf biasanya disebut...", jawaban: "Kobong", poin: 30 },
    { soal: "Singkatan dari Penerimaan Santri Baru pada lembaga pendidikan adalah...", jawaban: "PSB", poin: 30 },
    { soal: "MUI adalah singkatan dari Majelis Ulama...", jawaban: "Indonesia", poin: 20 },
    { soal: "Surah di dalam Al-Quran yang berarti 'Laba-laba' adalah...", jawaban: "Al-Ankabut", poin: 40 },
    { soal: "Sistem pendataan keluar masuknya buku di perpustakaan disebut sistem...", jawaban: "Sirkulasi", poin: 40 },
    { soal: "Nabi yang memiliki mukjizat bisa berbicara dengan hewan adalah...", jawaban: "Sulaiman", poin: 30 },
    { soal: "Air yang suci dan mensucikan dalam fiqih disebut air...", jawaban: "Mutlak", poin: 50 },
    { soal: "Hari raya kurban yang jatuh pada tanggal 10 Dzulhijjah disebut Idul...", jawaban: "Adha", poin: 20 },
    { soal: "Kitab kuning peninggalan ulama salaf yang membahas tata bahasa Arab adalah kitab...", jawaban: "Jurumiyah", poin: 60 },
    { soal: "Masjid tempat pertama kali turunnya perintah salat lima waktu kepada Nabi Muhammad adalah Masjidil...", jawaban: "Aqsa", poin: 40 },
    { soal: "Malaikat yang bertugas menjaga pintu surga adalah Malaikat...", jawaban: "Ridwan", poin: 30 },
    { soal: "Rukun iman yang keenam adalah iman kepada...", jawaban: "Qada dan Qadar", poin: 40 },
    { soal: "Perang pertama dalam sejarah Islam yang terjadi di bulan Ramadhan adalah perang...", jawaban: "Badar", poin: 50 },
    { soal: "Paman Nabi Muhammad SAW yang mati syahid dan dijuluki Singa Allah adalah...", jawaban: "Hamzah", poin: 60 },
    { soal: "Puasa sunah yang dikerjakan pada hari Senin dan Kamis disebut puasa...", jawaban: "Senin Kamis", poin: 20 },
    { soal: "Sahabat nabi yang menjadi khalifah pertama adalah...", jawaban: "Abu Bakar", poin: 30 },
    { soal: "Zakat yang wajib dikeluarkan pada bulan Ramadhan sebelum shalat Idul Fitri adalah zakat...", jawaban: "Fitrah", poin: 20 },
    { soal: "Nama lain dari hari kiamat yang berarti 'Hari Pembalasan' adalah Yaumul...", jawaban: "Jaza", poin: 50 },
    { soal: "Gelar Al-Amin yang disandang Nabi Muhammad SAW memiliki arti dapat...", jawaban: "Dipercaya", poin: 30 },

    // --- Teknologi, Coding & Server ---
    { soal: "Framework PHP dengan logo merah putih yang sangat populer untuk membuat website adalah...", jawaban: "Laravel", poin: 40 },
    { soal: "Sistem operasi server turunan Debian yang populer dan stabil adalah...", jawaban: "Ubuntu", poin: 40 },
    { soal: "Aplikasi web server saingan Apache yang terkenal cepat menangani banyak trafik adalah...", jawaban: "Nginx", poin: 50 },
    { soal: "Perintah firewall bawaan di Ubuntu yang sangat gampang disetting disingkat...", jawaban: "UFW", poin: 60 },
    { soal: "Protokol VPN modern yang terkenal sangat ringan dan cepat adalah...", jawaban: "WireGuard", poin: 60 },
    { soal: "Modul mikrokontroler berbasis ESP8266 yang sering dipakai untuk project IoT adalah...", jawaban: "NodeMCU", poin: 50 },
    { soal: "Teknologi kartu tap tanpa sentuh yang sering dipakai untuk e-Toll atau absensi adalah...", jawaban: "RFID", poin: 40 },
    { soal: "Program kecerdasan buatan yang otomatis membalas chat di grup WhatsApp disebut...", jawaban: "Bot", poin: 20 },
    { soal: "Istilah untuk mencari dan memperbaiki error pada kode program adalah...", jawaban: "Debugging", poin: 40 },
    { soal: "Apa kepanjangan dari API dalam dunia pemrograman?", jawaban: "Application Programming Interface", poin: 60 },
    { soal: "Platform hosting kode sumber yang logonya menyerupai kucing gurita adalah...", jawaban: "GitHub", poin: 30 },
    { soal: "Perintah di terminal Linux untuk berpindah direktori/folder adalah...", jawaban: "cd", poin: 30 },
    { soal: "Sistem pengelola database yang merupakan 'saudara kembar' dari MySQL adalah...", jawaban: "MariaDB", poin: 50 },
    { soal: "Layanan penyedia SSL gratis yang command-nya sering menggunakan Certbot adalah...", jawaban: "Let's Encrypt", poin: 50 },
    { soal: "Bahasa pemrograman yang paling sering digunakan untuk membuat interaksi di halaman web adalah...", jawaban: "JavaScript", poin: 30 },
    { soal: "Tag HTML yang digunakan untuk menampilkan gambar adalah...", jawaban: "img", poin: 20 },
    { soal: "Protokol standar untuk mentransfer file antara komputer dan server adalah...", jawaban: "FTP", poin: 40 },
    { soal: "Jenis serangan siber yang membanjiri server dengan trafik palsu hingga down disebut...", jawaban: "DDoS", poin: 50 },
    { soal: "Di Laravel, sistem untuk menghubungkan database dengan model berorientasi objek disebut...", jawaban: "Eloquent", poin: 70 },
    { soal: "Variabel khusus di PHP yang menampung data login pengguna di browser disebut...", jawaban: "Session", poin: 40 },

    // --- Nostalgia Game & Hiburan Tradisional ---
    { soal: "Game tebak-tebakan menebak kata di mana pemain menggambar sesuatu disebut...", jawaban: "Gartic", poin: 30 },
    { soal: "Kendaraan umum roda empat yang sering ngetem dan ugal-ugalan di jalanan adalah...", jawaban: "Angkot", poin: 20 },
    { soal: "Sebutan untuk orang yang menjadi bos atau pengusaha sate adalah...", jawaban: "Juragan", poin: 30 },
    { soal: "Kesenian boneka bayangan khas Jawa yang dimainkan oleh dalang adalah...", jawaban: "Wayang", poin: 20 },
    { soal: "Alat musik pukul tradisional dari perunggu yang bunyinya 'gong' dan 'kenong' adalah...", jawaban: "Gamelan", poin: 30 },
    { soal: "Permainan menerbangkan kertas dengan kerangka bambu yang sering diadu di langit adalah...", jawaban: "Layangan", poin: 20 },
    { soal: "Konsol game legendaris buatan Sony yang rilis tahun 2000 dan sangat laris adalah PlayStation...", jawaban: "2", poin: 30 },
    { soal: "Game mobile MOBA 5v5 yang sangat populer di Indonesia dengan hero seperti Miya dan Alucard adalah...", jawaban: "Mobile Legends", poin: 20 },
    { soal: "Permainan papan klasik yang tujuannya memonopoli petak tanah dan rumah adalah...", jawaban: "Monopoli", poin: 20 },
    { soal: "Dalam permainan catur, pion yang berhasil mencapai ujung papan lawan bisa berubah menjadi...", jawaban: "Menteri", poin: 40 }, // Atau Ratu
    { soal: "Karakter landak biru yang bisa berlari super cepat di game SEGA bernama...", jawaban: "Sonic", poin: 20 },
    { soal: "Game puzzle menyusun balok-balok yang berjatuhan dari atas ke bawah disebut...", jawaban: "Tetris", poin: 30 },
    { soal: "Seni bela diri melempar senjata rahasia (shuriken) khas ninja dari Jepang disebut...", jawaban: "Ninjutsu", poin: 50 },
    { soal: "Permainan anak tradisional melompat pada kotak-kotak yang digambar di tanah disebut...", jawaban: "Engklek", poin: 40 },
    { soal: "Senjata yang digunakan oleh karakter game Mario untuk mengalahkan musuhnya selain menginjak adalah menembakkan...", jawaban: "Api", poin: 40 },
    { soal: "Dalam kartu remi, simbol yang berbentuk daun berwarna hitam disebut...", jawaban: "Sekop", poin: 30 },
    { soal: "Burung pemarah berwarna merah yang suka menabrak babi hijau ada di game...", jawaban: "Angry Birds", poin: 20 },
    { soal: "Studio animasi Jepang legendaris pembuat film Spirited Away dan Totoro adalah Studio...", jawaban: "Ghibli", poin: 50 },
    { soal: "Permainan kartu Uno, jika ada pemain yang mengeluarkan kartu +4, pemain selanjutnya harus ambil berapa kartu?", jawaban: "4", poin: 10 },
    { soal: "Game simulasi membangun desa dan merampok desa lain yang ada karakter Barbarian dan Archer adalah...", jawaban: "Clash of Clans", poin: 30 },

    // --- Tebak-tebakan Receh & Plesetan (Level Bapak-bapak) ---
    { soal: "Kota apa yang rasanya selalu pahit?", jawaban: "Pare-pare", poin: 50 },
    { soal: "Ikan apa yang suka berhenti tiba-tiba?", jawaban: "Ikan paus", poin: 50 }, // Pause
    { soal: "Pulau apa yang nggak pernah sepi?", jawaban: "Pulau Seribu", poin: 50 },
    { soal: "Hewan apa yang bersaudara?", jawaban: "Katak beradik", poin: 60 },
    { soal: "Daun apa yang bikin orang sedih?", jawaban: "Daun leave me alone", poin: 60 }, // Don't leave me alone
    { soal: "Gendang apa yang nggak bisa dipukul?", jawaban: "Gendang telinga", poin: 40 },
    { soal: "Nasi apa yang nggak bisa dimakan?", jawaban: "Nasihat", poin: 40 },
    { soal: "Pohon apa yang paling berani?", jawaban: "Pohon pisang, jantungnya di luar", poin: 70 },
    { soal: "Lauk apa yang paling egois?", jawaban: "Tahu diri", poin: 60 },
    { soal: "Ban apa yang bisa makan, tidur, dan sekolah?", jawaban: "Banci", poin: 50 },
    { soal: "Sayur apa yang suka nelpon?", jawaban: "Sayur kol", poin: 40 }, // Call
    { soal: "Kuda apa yang jalannya selalu nunduk?", jawaban: "Kuda lumping nyari saweran", poin: 60 },
    { soal: "Lemari apa yang bisa masuk kantong?", jawaban: "Lema-ribu rupiah", poin: 50 },
    { soal: "Buah apa yang paling kaya?", jawaban: "Sri-kaya", poin: 40 },
    { soal: "Penyanyi yang rambutnya nggak pernah disisir?", jawaban: "Ayu Kusut", poin: 50 },
    { soal: "Buku apa yang nggak pernah dibaca orang dari halaman depan?", jawaban: "Buku tabungan", poin: 60 }, // Dilihat saldo belakangnya doang
    { soal: "Mata apa yang ukurannya sekitar 15 sentimeter?", jawaban: "Mata uang receh dijejerin", poin: 80 },
    { soal: "Kera apa yang bikin sakit?", jawaban: "Keram kaki", poin: 40 },
    { soal: "Bis apa yang bikin mabuk?", jawaban: "Bisikan maut", poin: 50 },
    { soal: "Jalan apa yang selalu mentok?", jawaban: "Jalan buntu", poin: 20 },

    // --- Tebak-tebakan Logika (Jebakan Batman) ---
    { soal: "Kalau tidur dia berdiri, kalau berdiri dia tidur. Apakah itu?", jawaban: "Jempol kaki", poin: 70 },
    { soal: "Berapa banyak tanah di dalam lubang berukuran 3x3x3 meter?", jawaban: "0", poin: 60 }, // Namanya juga lubang, nggak ada tanahnya
    { soal: "Jika diucapkan sekali dia jauh, diucapkan dua kali dia jadi dekat. Kata apakah itu?", jawaban: "Langit", poin: 80 }, // Langit-langit rumah
    { soal: "Kamu lari mengelilingi lapangan bola sejauh 5 putaran. Di mana kamu sekarang?", jawaban: "Di tempat semula", poin: 50 },
    { soal: "Mana yang lebih berat, 1 kg kapas atau 1 kg besi?", jawaban: "Sama berat", poin: 40 },
    { soal: "Orang buta melihatnya, orang tuli mendengarnya, orang bisu mengucapkannya. Apakah itu?", jawaban: "Tidak ada", poin: 80 },
    { soal: "Bisa dipegang pakai tangan kanan, tapi nggak bisa dipegang pakai tangan kiri. Apakah itu?", jawaban: "Siku kiri", poin: 70 },
    { soal: "Ketika dia hidup kita bernyanyi, ketika dia mati kita tepuk tangan. Apakah itu?", jawaban: "Lilin ulang tahun", poin: 60 },
    { soal: "Benda apa yang kalau siang hurufnya ada 5, kalau malam hurufnya ada 5 juga?", jawaban: "Benda", poin: 50 }, // Kata 'benda' hurufnya 5
    { soal: "Masuknya miring, keluarnya miring juga. Benda apakah itu?", jawaban: "Kancing baju", poin: 60 },
    { soal: "Semakin banyak kamu memberinya, semakin kecil dia. Benda apakah itu?", jawaban: "Rautan pensil", poin: 70 },
    { soal: "Maju terus nggak pernah mundur, tapi nggak pernah sampai tujuan. Apakah itu?", jawaban: "Waktu", poin: 50 },
    { soal: "Punya banyak kamar tapi nggak ada yang tidur di sana. Apakah itu?", jawaban: "Sarang lebah", poin: 70 },
    { soal: "Keluarga Pak Budi punya 6 anak laki-laki. Setiap anak laki-laki punya 1 saudara perempuan. Berapa jumlah anak Pak Budi?", jawaban: "7", poin: 80 }, // Saudara perempuannya cuma 1 untuk semuanya
    { soal: "Uang koin dilempar 10 kali, 9 kali muncul angka. Berapa persen kemungkinan muncul gambar pada lemparan ke-11?", jawaban: "50", poin: 60 }, // Peluang tetap 50% tiap lemparan
    { soal: "Di kamar ada 10 lalat. Dipukul mati 3. Sisa berapa lalat di kamar?", jawaban: "10", poin: 60 }, // Kan yang 3 mati tetap di kamar, 7 hidup di kamar
    { soal: "Siapa yang selalu memotong rambut orang tapi rambutnya sendiri nggak pernah gundul?", jawaban: "Tukang cukur", poin: 30 },
    { soal: "Apa yang kalau putih dibilang kotor, kalau hitam dibilang bersih?", jawaban: "Papan tulis", poin: 50 },
    { soal: "Kalau dikocok putihnya keluar. Apakah itu?", jawaban: "Tipe-x", poin: 60 },
    { soal: "Diinjak nggak bikin sakit, tapi bikin pincang. Apakah itu?", jawaban: "Tahi ayam", poin: 50 },

    // --- Pengetahuan Umum & Geografi Internasional ---
    { soal: "Negara manakah yang terkecil di dunia?", jawaban: "Vatikan", poin: 40 },
    { soal: "Gurun terluas di dunia (selain Antartika) adalah Gurun...", jawaban: "Sahara", poin: 30 },
    { soal: "Sungai terpanjang di benua Amerika adalah Sungai...", jawaban: "Amazon", poin: 30 },
    { soal: "Tembok Besar berada di negara...", jawaban: "China", poin: 20 },
    { soal: "Apa ibu kota dari negara Inggris?", jawaban: "London", poin: 20 },
    { soal: "Taj Mahal adalah monumen peninggalan bersejarah yang terletak di negara...", jawaban: "India", poin: 20 },
    { soal: "Pegunungan tertinggi di dunia adalah pegunungan...", jawaban: "Himalaya", poin: 40 },
    { soal: "Negara bagian di Amerika Serikat yang letaknya terpisah dan berupa kepulauan di tengah samudera adalah...", jawaban: "Hawaii", poin: 40 },
    { soal: "Mata uang yang digunakan oleh sebagian besar negara di benua Eropa adalah...", jawaban: "Euro", poin: 20 },
    { soal: "Gedung tertinggi di dunia saat ini, Burj Khalifa, berada di kota...", jawaban: "Dubai", poin: 30 },
    { soal: "Negara tetangga Indonesia yang memiliki ikon patung Merlion adalah...", jawaban: "Singapura", poin: 20 },
    { soal: "Benua yang sering dijuluki sebagai Benua Hitam adalah Benua...", jawaban: "Afrika", poin: 30 },
    { soal: "Samudera yang mengapit negara Indonesia selain Samudera Hindia adalah Samudera...", jawaban: "Pasifik", poin: 20 },
    { soal: "Apa ibu kota dari negara Mesir?", jawaban: "Kairo", poin: 40 },
    { soal: "Terusan yang menghubungkan Laut Tengah dan Laut Merah di Mesir adalah Terusan...", jawaban: "Suez", poin: 60 },
    { soal: "Negara yang berbatasan darat langsung dengan provinsi Kalimantan Barat adalah...", jawaban: "Malaysia", poin: 30 },
    { soal: "Suku asli yang mendiami benua Australia adalah suku...", jawaban: "Aborigin", poin: 30 },
    { soal: "Julukan Macan Asia sering ditujukan kepada negara...", jawaban: "Jepang", poin: 40 }, // Bisa juga Korsel/Taiwan/Singapura (Macan Asia Timur), tapi Jepang paling umum di trivia
    { soal: "Danau terdalam di dunia yang terletak di Rusia adalah Danau...", jawaban: "Baikal", poin: 70 },
    { soal: "Arah jarum kompas selalu menunjuk ke arah utara dan...", jawaban: "Selatan", poin: 10 },

    // --- Kewarganegaraan, Sejarah & Pahlawan ---
    { soal: "Pancasila disahkan pada tanggal 18 Agustus 1945 oleh organisasi bernama...", jawaban: "PPKI", poin: 50 },
    { soal: "Siapakah pencipta lagu Garuda Pancasila?", jawaban: "Sudharnoto", poin: 60 },
    { soal: "Naskah proklamasi kemerdekaan Indonesia diketik oleh...", jawaban: "Sayuti Melik", poin: 40 },
    { soal: "Organisasi pergerakan nasional pertama di Indonesia yang berdiri tahun 1908 adalah...", jawaban: "Budi Utomo", poin: 50 },
    { soal: "Presiden RI yang keempat adalah...", jawaban: "Abdurrahman Wahid", poin: 40 }, // Gus Dur
    { soal: "Mata uang negara Republik Indonesia yang pertama kali beredar setelah merdeka disebut...", jawaban: "ORI", poin: 60 }, // Oeang Republik Indonesia
    { soal: "Siapakah pahlawan nasional dari Aceh yang terkenal gigih melawan Belanda dan bergelar Cut?", jawaban: "Cut Nyak Dien", poin: 30 },
    { soal: "Rapat raksasa yang dilakukan rakyat Jakarta pasca proklamasi terjadi di Lapangan...", jawaban: "Ikada", poin: 60 },
    { soal: "Kota di Jepang yang dijatuhi bom atom pertama kali pada 6 Agustus 1945 adalah...", jawaban: "Hiroshima", poin: 40 },
    { soal: "Siapa nama wakil presiden pertama Republik Indonesia?", jawaban: "Mohammad Hatta", poin: 20 },
    { soal: "Kerajaan maritim terbesar di Nusantara yang berpusat di Sumatera Selatan adalah Sriwijaya. Kerajaan di Jawa Timur adalah...", jawaban: "Majapahit", poin: 30 },
    { soal: "Siapa panglima besar Jenderal yang memimpin perang gerilya melawan Belanda meski sedang sakit paru-paru?", jawaban: "Soedirman", poin: 30 },
    { soal: "Lembaga negara yang bertugas menguji undang-undang terhadap UUD 1945 adalah Mahkamah...", jawaban: "Konstitusi", poin: 40 },
    { soal: "Undang-Undang Dasar negara kita disahkan pada tahun...", jawaban: "1945", poin: 10 },
    { soal: "Pasukan elite yang bertugas mengamankan Presiden dan Wakil Presiden RI disebut...", jawaban: "Paspampres", poin: 30 },
    { soal: "Konferensi Asia Afrika pertama kali diselenggarakan di kota...", jawaban: "Bandung", poin: 40 },
    { soal: "Pahlawan dari Sulawesi Selatan yang dijuluki Ayam Jantan dari Timur adalah...", jawaban: "Sultan Hasanuddin", poin: 40 },
    { soal: "Sila ketiga Pancasila dilambangkan dengan gambar...", jawaban: "Pohon Beringin", poin: 20 },
    { soal: "Pada zaman penjajahan Belanda, sistem tanam paksa disebut dengan istilah...", jawaban: "Cultuurstelsel", poin: 60 },
    { soal: "Gubernur Jenderal Belanda yang membangun jalan raya pos dari Anyer sampai Panarukan adalah...", jawaban: "Daendels", poin: 50 },

    // --- Sains, Anatomi, & Flora Fauna ---
    { soal: "Sel kelamin betina pada bunga disebut...", jawaban: "Putik", poin: 40 },
    { soal: "Gas rumah kaca terbanyak yang menyebabkan pemanasan global adalah karbon...", jawaban: "Dioksida", poin: 30 },
    { soal: "Kelenjar terbesar dalam tubuh manusia yang berfungsi menetralkan racun adalah...", jawaban: "Hati", poin: 40 },
    { soal: "Proses keluarnya larva dari telur disebut...", jawaban: "Menetas", poin: 10 },
    { soal: "Hewan mamalia yang bisa terbang adalah...", jawaban: "Kelelawar", poin: 30 },
    { soal: "Alat pernapasan pada serangga seperti belalang adalah...", jawaban: "Trakea", poin: 50 },
    { soal: "Satuan ukur untuk mengukur kekuatan gempa bumi disebut Skala...", jawaban: "Richter", poin: 30 },
    { soal: "Ilmuwan yang menemukan gaya gravitasi karena apel jatuh di kepalanya adalah...", jawaban: "Isaac Newton", poin: 40 },
    { soal: "Lapisan udara yang menyelubungi bumi dan melindungi dari sinar UV disebut...", jawaban: "Atmosfer", poin: 30 },
    { soal: "Kandungan pada susu yang sangat baik untuk pertumbuhan tulang adalah...", jawaban: "Kalsium", poin: 20 },
    { soal: "Peristiwa perputaran bumi pada porosnya disebut...", jawaban: "Rotasi", poin: 30 },
    { soal: "Planet yang memiliki cincin yang paling jelas terlihat adalah planet...", jawaban: "Saturnus", poin: 30 },
    { soal: "Sifat magnet yang ujungnya selalu menunjuk ke utara dan selatan karena adanya medan...", jawaban: "Magnet", poin: 40 },
    { soal: "Tumbuhan memakan serangga untuk memenuhi kebutuhan zat nitrogen. Tumbuhan ini disebut...", jawaban: "Kantong semar", poin: 50 },
    { soal: "Berapa jumlah kaki pada laba-laba?", jawaban: "8", poin: 30 },
    { soal: "Logam cair yang biasa digunakan dalam termometer raksa adalah...", jawaban: "Raksa", poin: 40 },
    { soal: "Bagian mata yang berfungsi mengatur banyak sedikitnya cahaya yang masuk adalah...", jawaban: "Pupil", poin: 50 },
    { soal: "Proses perubahan uap air menjadi titik-titik air pembentuk awan disebut...", jawaban: "Kondensasi", poin: 60 },
    { soal: "Satu-satunya benda langit buatan manusia yang saat ini sudah keluar dari tata surya adalah satelit...", jawaban: "Voyager", poin: 70 },
    { soal: "Ulat sutera menghasilkan benang sutera dari kelenjar yang terdapat di dekat...", jawaban: "Mulut", poin: 60 },

    // --- Kuliner & Jajanan Khas Nusantara ---
    { soal: "Minuman tradisional khas Jawa Barat yang terbuat dari gula aren, santan, dan adonan sagu mutiara hijau adalah...", jawaban: "Cendol", poin: 20 },
    { soal: "Bahan utama pembuatan kue lapis legit yang membuatnya beraroma khas adalah bumbu...", jawaban: "Spekuk", poin: 50 },
    { soal: "Soto ayam yang disajikan dengan serbuk koya gurih adalah soto khas dari...", jawaban: "Lamongan", poin: 40 },
    { soal: "Nasi yang dimasak dengan santan, kunyit, dan rempah-rempah sehingga warnanya kuning disebut nasi...", jawaban: "Kuning", poin: 10 },
    { soal: "Jajanan pasar berbentuk seperti perahu berisi adonan tepung beras manis bersantan disebut kue...", jawaban: "Talam", poin: 60 }, // Atau kue perahu/tetel
    { soal: "Ayam geprek pertama kali dipopulerkan di kota...", jawaban: "Yogyakarta", poin: 50 },
    { soal: "Makanan mie berkuah kental khas Aceh kaya rempah sering disajikan dengan irisan daging...", jawaban: "Sapi", poin: 30 }, // Atau Kepiting
    { soal: "Kue kering berbentuk bulan sabit berselimut gula halus putih sering disebut kue...", jawaban: "Putri Salju", poin: 30 },
    { soal: "Sate khas Madura biasanya menggunakan daging ayam dan disiram dengan bumbu...", jawaban: "Kacang", poin: 20 },
    { soal: "Masakan olahan ikan berdaging tebal khas Batak yang dimasak dengan bumbu andaliman adalah ikan...", jawaban: "Arsik", poin: 60 },
    { soal: "Makanan ringan dari singkong yang difermentasi sehingga rasanya manis, berair, dan sedikit alkoholik adalah...", jawaban: "Tape", poin: 30 }, // Peuyeum
    { soal: "Gorengan tempe yang dibalut tepung dan digoreng setengah matang (lembek) khas Purwokerto disebut...", jawaban: "Mendoan", poin: 20 },
    { soal: "Roti berbentuk buaya yang wajib ada di pernikahan adat Betawi disebut Roti...", jawaban: "Buaya", poin: 20 },
    { soal: "Minuman penghangat tubuh khas Sunda yang terbuat dari jahe, gula merah, dan kelapa sangrai disebut...", jawaban: "Bandrek", poin: 40 },
    { soal: "Soto khas Makassar yang isinya jeroan sapi berdaging tebal dan kuahnya kental disebut...", jawaban: "Coto", poin: 30 },
    { soal: "Sambal matah adalah sambal mentah yang berasal dari pulau...", jawaban: "Bali", poin: 20 },
    { soal: "Kue pancong terbuat dari campuran tepung beras dan kelapa parut. Makanan ini dimasak menggunakan cetakan...", jawaban: "Setengah lingkaran", poin: 50 }, // Bentuknya
    { soal: "Olahan mi kuning tebal yang ditumis dengan kecap manis dan seafood khas Jawa disebut Mi...", jawaban: "Jawa", poin: 30 },
    { soal: "Sayur asam memiliki rasa asam yang berasal dari buah...", jawaban: "Asam Jawa", poin: 20 },
    { soal: "Bahan pengental alami dari rumput laut yang sering dibuat dessert kenyal adalah...", jawaban: "Agar-agar", poin: 20 },

    // --- Bahasa, Sastra, Seni & Olahraga ---
    { soal: "Kata ganti orang ketiga tunggal dalam bahasa Indonesia adalah...", jawaban: "Dia", poin: 20 },
    { soal: "Majas yang melebih-lebihkan suatu keadaan disebut majas...", jawaban: "Hiperbola", poin: 40 },
    { soal: "Lanjutkan peribahasa ini: 'Besar pasak daripada...'", jawaban: "Tiang", poin: 20 },
    { soal: "Sajak 4 baris yang bersajak a-b-a-b dinamakan...", jawaban: "Pantun", poin: 20 },
    { soal: "Lawan kata (antonim) dari kata 'fiktif' adalah...", jawaban: "Nyata", poin: 30 }, // Atau faktual
    { soal: "Gaya renang yang paling lambat tetapi hemat energi adalah gaya...", jawaban: "Dada", poin: 40 }, // Gaya katak
    { soal: "Pelanggaran dalam bola basket saat pemain berjalan tanpa memantulkan bola disebut...", jawaban: "Traveling", poin: 50 },
    { soal: "Jumlah base atau titik aman dalam permainan bisbol atau kasti adalah...", jawaban: "4", poin: 40 },
    { soal: "Olahraga bela diri tinju dilakukan di atas area berbentuk persegi yang disebut...", jawaban: "Ring", poin: 20 },
    { soal: "Alat yang digunakan pesenam untuk melompat tinggi dan melakukan salto disebut...", jawaban: "Trampolin", poin: 30 },
    { soal: "Dalam permainan bulu tangkis, pukulan pelan yang bertujuan menjatuhkan shuttlecock dekat net disebut pukulan...", jawaban: "Dropshot", poin: 50 },
    { soal: "Kata 'Bhineka' pada semboyan negara kita memiliki arti...", jawaban: "Berbeda-beda", poin: 20 },
    { soal: "Arti dari peribahasa 'Ada udang di balik batu' adalah ada suatu...", jawaban: "Maksud tersembunyi", poin: 40 },
    { soal: "Pola lantai melingkar pada tari kecak bermakna tentang kekompakan dan...", jawaban: "Kesatuan", poin: 60 },
    { soal: "Warna sekunder dari campuran warna merah dan kuning adalah warna...", jawaban: "Oranye", poin: 20 },
    { soal: "Tangga nada yang terdiri dari tujuh nada dasar (do re mi fa sol la si) disebut tangga nada...", jawaban: "Diatonis", poin: 50 },
    { soal: "Cabang olahraga atletik tolak peluru menggunakan bola berat yang terbuat dari...", jawaban: "Besi", poin: 30 },
    { soal: "Ajang pertandingan olahraga untuk penyandang disabilitas tingkat dunia disebut...", jawaban: "Paralimpiade", poin: 50 },
    { soal: "Novel populer 'Bumi Manusia' ditulis oleh sastrawan besar Indonesia bernama Pramoedya Ananta...", jawaban: "Toer", poin: 60 },
    { soal: "Tanda baca yang digunakan untuk mengakhiri kalimat seruan atau perintah adalah tanda...", jawaban: "Seru", poin: 10 },

    // --- Dunia IT, Web & Server ---
    { soal: "Perintah command line bawaan di framework Laravel disebut...", jawaban: "Artisan", poin: 40 },
    { soal: "Software web server yang logonya berwarna hijau dan sering dipakai bersanding dengan Apache adalah...", jawaban: "Nginx", poin: 40 },
    { soal: "Tool gratis dari Let's Encrypt untuk memasang sertifikat SSL di server Ubuntu disebut...", jawaban: "Certbot", poin: 50 },
    { soal: "Protokol VPN modern berlogo naga merah yang terkenal cepat dan ringan untuk SSH adalah...", jawaban: "WireGuard", poin: 60 },
    { soal: "Perintah dasar untuk mengamankan port (firewall) di Linux Ubuntu adalah...", jawaban: "UFW", poin: 50 },
    { soal: "Modul mikrokontroler berbasis ESP8266 berlogo laba-laba yang sering dipakai untuk project IoT adalah...", jawaban: "NodeMCU", poin: 50 },
    { soal: "Teknologi kartu pintar tanpa kontak fisik yang sering dipadukan dengan NodeMCU untuk absensi adalah...", jawaban: "RFID", poin: 40 },
    { soal: "Layanan HTTP API pihak ketiga yang sering dipakai developer untuk membuat bot WhatsApp secara tidak resmi adalah...", jawaban: "WAHA", poin: 60 },
    { soal: "Package manager bawaan untuk bahasa pemrograman PHP adalah...", jawaban: "Composer", poin: 40 },
    { soal: "Format ringan pertukaran data yang sering dipakai oleh REST API selain XML adalah...", jawaban: "JSON", poin: 30 },
    { soal: "Port jaringan default untuk melakukan koneksi aman (SSH) ke VPS adalah port...", jawaban: "22", poin: 40 },
    { soal: "Alamat IP 127.0.0.1 di komputer sering juga disebut dengan istilah...", jawaban: "Localhost", poin: 30 },
    { soal: "Perintah dasar Linux untuk melihat daftar isi dari sebuah direktori/folder adalah...", jawaban: "ls", poin: 30 },
    { soal: "Fitur untuk menjadwalkan task atau script secara otomatis di server Linux disebut...", jawaban: "Cronjob", poin: 50 },
    { soal: "Cabang atau branch utama (default) di dalam sebuah repository Git biasanya bernama...", jawaban: "Main", poin: 40 }, // atau Master
    { soal: "Bahasa kueri standar untuk mengambil dan memanipulasi data di database relasional adalah...", jawaban: "SQL", poin: 30 },
    { soal: "File tersembunyi untuk menyimpan konfigurasi environment pada project Laravel biasanya bernama...", jawaban: ".env", poin: 40 },
    { soal: "Layanan penyewaan server virtual yang populer dan biasa disingkat VPS kepanjangannya adalah...", jawaban: "Virtual Private Server", poin: 30 },
    { soal: "Direktori default root web server pada Ubuntu biasanya berada di folder /var/www/...", jawaban: "html", poin: 40 },
    { soal: "Proses mengunggah aplikasi dari komputer lokal ke server agar bisa diakses online disebut...", jawaban: "Deploy", poin: 30 },

    // --- Kehidupan Pesantren & Islami ---
    { soal: "Sebutan khas untuk ruangan asrama tempat santri tidur dan belajar (terutama di tatar Sunda) adalah...", jawaban: "Kobong", poin: 30 },
    { soal: "Sistem aplikasi di pesantren yang menangani pendaftaran awal masuk sering disingkat...", jawaban: "PSB", poin: 30 },
    { soal: "Ilmu yang mempelajari tata cara membaca huruf Al-Quran dengan baik dan benar disebut ilmu...", jawaban: "Tajwid", poin: 20 },
    { soal: "Hukum bacaan nun mati bertemu huruf ba' sehingga suaranya mendengung menyerupai huruf mim disebut...", jawaban: "Iqlab", poin: 50 },
    { soal: "Kitab kuning dasar yang membahas tata bahasa Arab (Nahwu) karangan Syekh ash-Shanhaji yang wajib dihapal santri adalah...", jawaban: "Jurumiyah", poin: 70 },
    { soal: "Sebutan untuk orang yang memimpin salat berjamaah di depan adalah...", jawaban: "Imam", poin: 10 },
    { soal: "Makmum yang tertinggal rakaat saat mengikuti salat berjamaah disebut makmum...", jawaban: "Masbuk", poin: 30 },
    { soal: "Bersuci menggunakan debu atau tanah suci karena tidak ada air disebut...", jawaban: "Tayammum", poin: 30 },
    { soal: "Batas tempat berpakaian ihram dan berniat bagi jemaah haji atau umrah disebut...", jawaban: "Miqat", poin: 60 },
    { soal: "Lari-lari kecil antara bukit Safa dan Marwah dalam rangkaian ibadah haji disebut...", jawaban: "Sa'i", poin: 40 },
    { soal: "Surah terakhir dalam urutan mushaf Al-Quran (Surah ke-114) adalah Surah...", jawaban: "An-Nas", poin: 20 },
    { soal: "Jumlah nama-nama Allah yang baik dan indah (Asmaul Husna) ada...", jawaban: "99", poin: 20 },
    { soal: "Nabi yang diberi mukjizat berupa perahu/bahtera besar untuk menyelamatkan umatnya dari banjir bandang adalah Nabi...", jawaban: "Nuh", poin: 20 },
    { soal: "Perintah wajib berpuasa di bulan Ramadhan tertulis di Al-Quran surah Al-Baqarah ayat ke-...", jawaban: "183", poin: 50 },
    { soal: "Sedekah berupa makanan pokok yang wajib dikeluarkan pada akhir Ramadhan adalah Zakat...", jawaban: "Fitrah", poin: 20 },
    { soal: "Hari-hari yang diharamkan berpuasa (tanggal 11, 12, 13 Dzulhijjah) disebut hari...", jawaban: "Tasyrik", poin: 40 },
    { soal: "Peristiwa peringatan turunnya wahyu Al-Quran pertama kali kepada Nabi Muhammad disebut...", jawaban: "Nuzulul Quran", poin: 40 },
    { soal: "Ibadah berjalan mengelilingi Ka'bah sebanyak tujuh kali putaran disebut...", jawaban: "Thawaf", poin: 30 },
    { soal: "Khalifah ketiga yang berjasa membukukan dan menyeragamkan bacaan mushaf Al-Quran adalah...", jawaban: "Utsman bin Affan", poin: 50 },
    { soal: "Orang yang melantunkan panggilan salat (azan) di masjid disebut...", jawaban: "Muadzin", poin: 10 },

    // --- Nostalgia Web Game, Budaya & Hiburan ---
    { soal: "Permainan tradisional Jawa Barat dengan batang bambu yang digoyang-goyang adalah...", jawaban: "Angklung", poin: 20 },
    { soal: "Saat bermain adu layangan, bagian benang tajam berlapis bubuk kaca yang sangat menentukan kemenangan disebut benang...", jawaban: "Gelasan", poin: 30 },
    { soal: "Alat musik ensambel tradisional dari Jawa berbahan perunggu yang memunculkan 'gema' khas adalah...", jawaban: "Gamelan", poin: 30 },
    { soal: "Pusat pemerintahan di tingkat desa yang sering dikelilingi gerobak jajanan seperti juragan sate atau bakso adalah...", jawaban: "Kelurahan", poin: 30 },
    { soal: "Transportasi umum perkotaan yang identik dengan ngetem, musik kencang, dan kejar-kejaran penumpang adalah...", jawaban: "Angkot", poin: 20 },
    { soal: "Kesenian menceritakan legenda masa lalu menggunakan media bayangan boneka kulit disebut...", jawaban: "Wayang", poin: 20 },
    { soal: "Karakter figuran di dalam dunia game yang mondar-mandir tapi tidak bisa dimainkan pemain disebut...", jawaban: "NPC", poin: 40 },
    { soal: "Singkatan dari bar darah (Health Points) karakter dalam game RPG adalah...", jawaban: "HP", poin: 20 },
    { soal: "Saat experience point karakter kita sudah penuh dan naik tingkat, hal ini disebut...", jawaban: "Level Up", poin: 20 },
    { soal: "Celah kerusakan/error pada kode game yang kadang malah bikin efek lucu atau menguntungkan pemain disebut...", jawaban: "Glitch", poin: 50 },
    { soal: "Pesan rahasia, referensi, atau lelucon tersembunyi yang sengaja dimasukkan developer ke dalam game disebut...", jawaban: "Easter Egg", poin: 50 },
    { soal: "Pemain game online yang karakternya diam saja karena orangnya ninggalin keyboard disebut...", jawaban: "AFK", poin: 30 },
    { soal: "Layar peringatan menyeramkan di akhir permainan yang berarti Anda kalah dan harus mengulang adalah...", jawaban: "Game Over", poin: 10 },
    { soal: "Bentuk pusaka atau senjata genggam khas masyarakat Sunda yang ujungnya melengkung estetis disebut...", jawaban: "Kujang", poin: 40 },
    { soal: "Genre game di mana Anda memerankan satu karakter utama, punya stats, quest, dan menjelajahi dunia adalah...", jawaban: "RPG", poin: 40 },
    { soal: "Batu alam, ritual mistis, dan tersesat di rimba adalah elemen yang sering muncul di game bergenre...", jawaban: "Horor", poin: 30 },
    { soal: "Mata uang virtual (koin) di dalam game Roblox yang sangat diminati anak-anak adalah...", jawaban: "Robux", poin: 40 },
    { soal: "Tarian singa barong dengan bulu merak raksasa yang membutuhkan kekuatan leher luar biasa berasal dari daerah...", jawaban: "Ponorogo", poin: 40 },
    { soal: "Sebutan untuk game simulasi di mana pemain harus mengatur stok barang, keuangan, dan bisnis keluarga adalah game...", jawaban: "Manajemen", poin: 30 },
    { soal: "Ucapan kekeluargaan antar pemain setelah menyelesaikan mabar dengan sportif biasanya disingkat...", jawaban: "GG", poin: 20 }, // Good Game

    // --- Tebak-tebakan Logika & Matematika Tipuan ---
    { soal: "Di meja ada 3 buah mangga. Kalau kamu ambil 2, sekarang kamu punya berapa mangga?", jawaban: "2", poin: 40 }, // Karena kamu ambil 2
    { soal: "Apa yang terus bertambah naik tapi tidak pernah bisa turun kembali?", jawaban: "Umur", poin: 30 },
    { soal: "Benda apa yang kalau dibalik posisinya, nilainya akan bertambah besar?", jawaban: "Angka 6", poin: 50 },
    { soal: "Ayah membelikan 12 buku tulis, Ibu membelikan 10 pensil gambar. Siapa yang harus bayar semuanya?", jawaban: "Kasir", poin: 60 },
    { soal: "Mana yang lebih berat saat ditimbang, 100 kg besi murni atau 100 kg kapas halus?", jawaban: "Sama berat", poin: 20 },
    { soal: "Saat dijemur dia basah, saat dipakai untuk mengeringkan dia malah ikut basah. Benda apakah itu?", jawaban: "Handuk", poin: 30 },
    { soal: "Dalam rumah ada 1 kakek, 1 nenek, 2 ayah, 2 ibu, 4 anak, dan 3 cucu. Berapa jumlah orang paling sedikit di ruang itu?", jawaban: "7", poin: 70 }, // 1 kakek, 1 nenek, 2 anak mereka (sepasang suami istri), dan 3 cucu.
    { soal: "Punya leher panjang tapi tak punya kepala. Punya badan lebar tapi tak punya tangan. Apakah itu?", jawaban: "Botol", poin: 40 },
    { soal: "Siapa yang punya 21 mata di sekujur badannya tapi tidak bisa melihat apa-apa?", jawaban: "Dadu", poin: 50 },
    { soal: "Jika 1=5, 2=15, 3=30, 4=50, maka angka 5 = ?", jawaban: "1", poin: 70 }, // Karena 1=5, maka 5=1
    { soal: "Binatang apa yang kakinya di kepala, badannya di kepala, dan matanya di kepala?", jawaban: "Kutu rambut", poin: 50 },
    { soal: "Sakitnya ringan, obatnya mudah dicari, tapi tidak ada satu pun orang di dunia yang kebal dengan penyakit ini. Apa itu?", jawaban: "Pilek", poin: 60 },
    { soal: "Kata apa dalam kamus bahasa Indonesia yang pengejaannya selalu salah?", jawaban: "Salah", poin: 50 },
    { soal: "Kamu masuk ke gua gelap, hanya punya 1 batang korek api. Di dalam ada lilin, lampu petromaks, dan kayu bakar. Apa yang kamu nyalakan duluan?", jawaban: "Korek api", poin: 50 },
    { soal: "Punya banyak lubang kecil di sekujur tubuhnya, tapi benda ini sangat hebat menahan air. Apakah itu?", jawaban: "Spons", poin: 40 },
    { soal: "Kalau kamu melempar batu bata merah ke laut biru yang sangat dalam, batunya jadi apa?", jawaban: "Jadi basah", poin: 30 },
    { soal: "Kereta listrik melaju dengan kecepatan 100 km/jam ke arah utara, angin berhembus ke arah selatan. Ke arah mana asap keretanya mengepul?", jawaban: "Kereta listrik tidak ada asapnya", poin: 50 },
    { soal: "Benda ini dibeli untuk makan siang, tapi anehnya tidak pernah dimakan. Benda apakah itu?", jawaban: "Piring", poin: 40 },
    { soal: "Malam hari bentuknya huruf O, tapi kalau di balik jadi huruf V. Hewan apakah itu?", jawaban: "Burung hantu", poin: 70 }, // Mata melotot (O), alis/paruh (V) - agak receh.
    { soal: "Hewan apa yang walau sudah dipotong kepalanya ratusan kali, dia akan tetap hidup?", jawaban: "Cacing", poin: 50 },

    // --- Tebak-tebakan Receh & Bapak-bapak ---
    { soal: "Kucing apa yang kalau diajak ngobrol bawaannya emosi terus?", jawaban: "Kucinggungan", poin: 50 }, // Tersinggungan
    { soal: "Buah apa yang paling disiplin, rajin, dan selalu datang pagi-pagi?", jawaban: "Apel pagi", poin: 40 },
    { soal: "Ikan apa yang matanya besar banget?", jawaban: "Ikan koki", poin: 20 },
    { soal: "Lalu, ikan apa yang bisa terbang mengudara?", jawaban: "Ikan indosiar", poin: 60 }, // Referensi logo Indosiar lama
    { soal: "Ban mobil apa yang nggak bisa dikempesin tapi bisa bikin kenyang kalau digigit?", jawaban: "Bandeng", poin: 40 },
    { soal: "Sepatu apa yang dipakai selamanya dan nggak bisa jalan?", jawaban: "Sepatung", poin: 40 },
    { soal: "Hewan apa yang kalau kumpul paling hening dan sopan?", jawaban: "Semute", poin: 50 }, // Mute
    { soal: "Kopi apa yang rasanya paling membahagiakan di dunia?", jawaban: "Kopinang kau dengan bismillah", poin: 60 },
    { soal: "Mobil apa yang suka bikin hati galau dan sedih?", jawaban: "Mobilang rindu tapi takut ditolak", poin: 60 },
    { soal: "Pohon apa yang paling rindang tapi nggak pernah punya ranting dan daun sama sekali?", jawaban: "Pohon silsilah keluarga", poin: 50 },
    { soal: "Sayur apa yang selalu muncul di adegan terakhir sebuah film atau cerita?", jawaban: "To-mat", poin: 40 }, // Tamat
    { soal: "Menurut fisika bapak-bapak, kenapa matahari setiap sore selalu tenggelam?", jawaban: "Karena nggak bisa berenang", poin: 50 },
    { soal: "Sapi apa yang warnanya bisa macam-macam dan pandai melukis?", jawaban: "Sapidol", poin: 30 },
    { soal: "Gajah apa yang belalainya sangat pendek dan pipih?", jawaban: "Gajah pesek", poin: 30 },
    { soal: "Hantu pocong apa yang paling ditunggu-tunggu sama emak-emak di pasar?", jawaban: "Pocongan harga", poin: 40 }, // Potongan
    { soal: "Jin apa yang nggak sakti dan nggak bisa mengabulkan satupun permintaan?", jawaban: "Jins levis", poin: 30 },
    { soal: "Pintu apa yang mau didorong oleh 100 orang berotot kawat tetep nggak bakal kebuka?", jawaban: "Pintu yang ada tulisan 'Tarik'", poin: 40 },
    { soal: "Kesenian debus apa yang sangat wangi dan disukai wanita?", jawaban: "Debus mandi", poin: 50 }, // Sabun mandi
    { soal: "Matahari apa yang diskonnya paling gede?", jawaban: "Matahari Department Store", poin: 20 },
    { soal: "Penyakit apa yang suka ada di drama Korea?", jawaban: "Ti-pus", poin: 40 }, // Oppa

    // --- Pengetahuan Umum & Geografi Indonesia ---
    { soal: "Provinsi pecahan Jawa Barat yang memiliki ibukota di Serang adalah...", jawaban: "Banten", poin: 20 },
    { soal: "Gunung berapi di Sumbawa yang letusannya pada tahun 1815 menyebabkan tahun tanpa musim panas di Eropa adalah Gunung...", jawaban: "Tambora", poin: 50 },
    { soal: "Sungai terpanjang di Indonesia yang membelah pedalaman Kalimantan Barat adalah Sungai...", jawaban: "Kapuas", poin: 40 },
    { soal: "Rumah adat masyarakat Minangkabau di Sumatera Barat dengan atap runcing seperti tanduk kerbau disebut Rumah...", jawaban: "Gadang", poin: 20 },
    { soal: "Tutup kepala adat pria khas masyarakat Jawa Tengah dan Yogyakarta yang memiliki tonjolan di belakang disebut...", jawaban: "Blangkon", poin: 20 },
    { soal: "Bandara udara internasional terbesar di Indonesia yang terletak di Kabupaten Tangerang bernama Bandara...", jawaban: "Soekarno-Hatta", poin: 20 },
    { soal: "Suku asli yang mendiami pegunungan Kendeng di Banten dan sangat membatasi diri dari teknologi modern adalah suku...", jawaban: "Baduy", poin: 30 },
    { soal: "Monumen ikonik kota Jakarta yang memiliki tugu peringatan dengan puncak api berlapis emas adalah...", jawaban: "Monas", poin: 10 },
    { soal: "Danau vulkanik di Gunung Kelimutu, Pulau Flores, NTT yang sangat terkenal di dunia adalah danau...", jawaban: "Tiga warna", poin: 40 },
    { soal: "Istana tempat peristirahatan kepresidenan RI yang halamannya dipenuhi rusa di Jawa Barat bernama Istana...", jawaban: "Bogor", poin: 20 },
    { soal: "Jembatan kabel terpanjang di Indonesia yang menghubungkan kota Surabaya dan Pulau Madura disebut Jembatan...", jawaban: "Suramadu", poin: 30 },
    { soal: "Kota di Kalimantan Barat yang dilalui garis nol derajat (Khatulistiwa) dan memiliki tugu peringatannya adalah kota...", jawaban: "Pontianak", poin: 30 },
    { soal: "Taman Nasional di ujung barat pulau Jawa yang menjadi rumah konservasi badak bercula satu adalah Taman Nasional...", jawaban: "Ujung Kulon", poin: 40 },
    { soal: "Pahlawan revolusi korban G30S/PKI dengan pangkat Jenderal yang dimasukkan ke sumur Lubang Buaya adalah Jenderal...", jawaban: "Ahmad Yani", poin: 40 },
    { soal: "Koin pecahan Rp 1000 lama bimetal (tahun 1993) menampilkan relief pohon...", jawaban: "Kelapa Sawit", poin: 40 },
    { soal: "Pelabuhan utama penyeberangan jalur darat dari Pulau Jawa menuju Pulau Bali bernama Pelabuhan...", jawaban: "Ketapang", poin: 30 },
    { soal: "Candi Prambanan yang megah merupakan kompleks candi peninggalan bercorak agama...", jawaban: "Hindu", poin: 20 },
    { soal: "Nama resmi organisasi yang memayungi seluruh kegiatan pramuka di tingkat nasional adalah...", jawaban: "Kwarnas", poin: 50 },
    { soal: "Nama tarian perang dari Papua yang dibawakan oleh penari pria dengan menggunakan busana adat dan senjata busur adalah tari...", jawaban: "Sajian", poin: 60 }, // Atau Tari Perang
    { soal: "Mantan Presiden RI yang merupakan insinyur penerbangan dan pendiri industri pesawat N-250 Gatot Kaca adalah...", jawaban: "B.J. Habibie", poin: 20 },

    // --- Sains, Biologi Dasar & Alam Semesta ---
    { soal: "Bunyi pantulan yang terdengar jelas setelah bunyi aslinya selesai diucapkan disebut...", jawaban: "Gema", poin: 20 },
    { soal: "Benda langit besar di tata surya yang mampu melakukan reaksi fusi dan memancarkan cahayanya sendiri disebut...", jawaban: "Bintang", poin: 30 },
    { soal: "Komponen darah yang memiliki tugas utama mengangkut oksigen ke seluruh sel tubuh adalah sel darah...", jawaban: "Merah", poin: 20 },
    { soal: "Lapisan terluar dari struktur bumi tempat manusia, laut, dan gunung berpijak disebut...", jawaban: "Kerak bumi", poin: 30 },
    { soal: "Simbol kimia H2O merupakan rumus baku untuk menyebut senyawa...", jawaban: "Air", poin: 20 },
    { soal: "Bagian partikel terkecil penyusun suatu materi yang tidak bisa dibagi lagi secara fisik disebut...", jawaban: "Atom", poin: 40 },
    { soal: "Pigmen hijau daun pada tumbuhan yang berfungsi menyerap cahaya untuk fotosintesis disebut...", jawaban: "Klorofil", poin: 30 },
    { soal: "Siklus memakan dan dimakan antar makhluk hidup secara berurutan dalam suatu ekosistem disebut rantai...", jawaban: "Makanan", poin: 20 },
    { soal: "Proses perubahan bentuk tubuh secara radikal pada serangga dari fase telur hingga hewan dewasa disebut...", jawaban: "Metamorfosis", poin: 20 },
    { soal: "Satuan internasional untuk mengukur besaran kuat arus listrik adalah...", jawaban: "Ampere", poin: 40 },
    { soal: "Sumber energi listrik yang bersumber dari panas bumi sering disebut energi...", jawaban: "Geotermal", poin: 50 },
    { soal: "Pembuluh darah yang bertugas membawa aliran darah kotor dari tubuh kembali menuju jantung disebut pembuluh...", jawaban: "Vena", poin: 40 },
    { soal: "Planet yang tanahnya kaya akan oksida besi sehingga dijuluki 'Planet Merah' adalah planet...", jawaban: "Mars", poin: 20 },
    { soal: "Warna putih pada cahaya matahari yang dibiaskan oleh tetesan air hujan akan terurai menjadi berapa spektrum warna utama?", jawaban: "7", poin: 20 },
    { soal: "Katak dan salamander termasuk dalam kelompok hewan bertulang belakang yang hidup di air dan darat, yaitu hewan...", jawaban: "Amfibi", poin: 20 },
    { soal: "Otot utama berupa sekat yang membatasi rongga dada dan rongga perut pada pernapasan perut disebut...", jawaban: "Diafragma", poin: 50 },
    { soal: "Enzim yang terdapat di air liur manusia untuk mengubah amilum (karbohidrat) menjadi gula sederhana adalah enzim...", jawaban: "Amilase", poin: 60 }, // Atau Ptialin
    { soal: "Magnet buatan sementara yang dibentuk dengan cara melilitkan paku tembaga dan dialiri arus baterai disebut...", jawaban: "Elektromagnet", poin: 50 },
    { soal: "Satuan pengukur besaran intensitas suara atau tingkat kebisingan lingkungan adalah...", jawaban: "Desibel", poin: 40 },
    { soal: "Hormon yang diproduksi oleh pankreas untuk mengendalikan kadar gula darah manusia adalah hormon...", jawaban: "Insulin", poin: 50 },

    // --- Bahasa Indonesia, Sastra & Sejarah Dunia ---
    { soal: "Dua kata berbeda yang memiliki kesamaan makna (padanan kata) dalam bahasa Indonesia disebut...", jawaban: "Sinonim", poin: 20 },
    { soal: "Karya sastra berupa karangan bebas yang bahasanya tidak terikat oleh rima, matra, dan bait disebut...", jawaban: "Prosa", poin: 40 },
    { soal: "Gaya bahasa yang menggunakan kata-kata kebalikan dari maksud sebenarnya untuk menyindir secara halus adalah majas...", jawaban: "Ironi", poin: 50 },
    { soal: "Lanjutkan pepatah klasik berikut: 'Air beriak tanda tak...'?", jawaban: "Dalam", poin: 20 },
    { soal: "Imbuhan awalan 'me-' jika dilekatkan pada kata dasar 'sapu' akan berubah bentuk menjadi...", jawaban: "Menyapu", poin: 20 },
    { soal: "Puisi perlawanan paling ikonik karya penyair Chairil Anwar berbunyi: 'Aku Ini Binatang...'", jawaban: "Jalang", poin: 40 },
    { soal: "Jenis cerita dongeng rakyat zaman dahulu yang menceritakan asal usul terjadinya suatu tempat atau gunung disebut...", jawaban: "Legenda", poin: 30 },
    { soal: "Kisah fiksi yang semua tokoh pahlawan atau penjahatnya diperankan oleh hewan yang bisa berbicara disebut...", jawaban: "Fabel", poin: 20 },
    { soal: "Kalimat yang susunan subjek dan predikatnya berantakan sehingga menimbulkan makna ganda atau membingungkan disebut kalimat...", jawaban: "Ambiguitas", poin: 50 }, // Ambigu / Rancu
    { soal: "Lanjutkan peribahasa motivasi ini: 'Berakit-rakit ke hulu, berenang-renang ke...'", jawaban: "Tepian", poin: 20 },
    { soal: "Benua di bumi selatan yang sangat terisolasi dan menjadi habitat endemik hewan mamalia berkantung adalah benua...", jawaban: "Australia", poin: 30 },
    { soal: "Perang Dunia II di kawasan Asia Pasifik berakhir setelah dua kota besar di Jepang dijatuhi bom atom pada bulan...", jawaban: "Agustus", poin: 40 },
    { soal: "Tembok pemisah ideologi yang membelah negara Jerman Barat dan Jerman Timur akhirnya diruntuhkan pada tahun...", jawaban: "1989", poin: 60 },
    { soal: "Raja Firaun kuno yang memerintahkan pembangunan piramida terbesar (Great Pyramid) di Giza adalah Raja...", jawaban: "Khufu", poin: 60 }, // Atau Cheops
    { soal: "Kekaisaran kuno raksasa yang berpusat di benua Eropa (Italia) dan meninggalkan bangunan arena gladiator Colosseum adalah Kekaisaran...", jawaban: "Romawi", poin: 30 },
    { soal: "Ilmuwan Amerika yang sering diakui (meski ada perdebatan) sebagai penemu dan pematen bola lampu pijar komersial adalah...", jawaban: "Thomas Alva Edison", poin: 30 },
    { soal: "Tokoh pembebasan Afrika Selatan yang dipenjara puluhan tahun dan sukses mengakhiri sistem rasisme Apartheid adalah...", jawaban: "Nelson Mandela", poin: 40 },
    { soal: "Ratu Mesir kuno terakhir yang sangat cerdas, terkenal karena kecantikannya dan sejarah asmaranya dengan Julius Caesar adalah...", jawaban: "Cleopatra", poin: 40 },
    { soal: "Bapak Proklamator Republik Indonesia ada dua orang yang menandatangani naskah, yaitu Ir. Soekarno dan Drs. Moh...", jawaban: "Hatta", poin: 10 },
    { soal: "Pertempuran darat terdahsyat pasca proklamasi di Surabaya pada tanggal 10 November 1945 diperingati sebagai Hari...", jawaban: "Pahlawan", poin: 20 },

    // --- Kuliner Dunia & Jajanan Pasar ---
    { soal: "Makanan praktis khas Jepang berupa nasi kepal berbentuk segitiga yang dibalut lembaran rumput laut (nori) disebut...", jawaban: "Onigiri", poin: 30 },
    { soal: "Olahan daging sapi tebal khas Minangkabau yang dimasak berjam-jam dengan santan murni hingga kering dan kehitaman adalah...", jawaban: "Rendang", poin: 10 },
    { soal: "Lauk pelengkap khas Korea Selatan berupa fermentasi sawi putih berlumur bumbu pedas kemerahan disebut...", jawaban: "Kimchi", poin: 20 },
    { soal: "Roti panggang berukuran sangat panjang asal Prancis yang memiliki tekstur kerak luar sangat keras disebut roti...", jawaban: "Baguette", poin: 50 },
    { soal: "Pasta populer khas benua Eropa (Italia) yang berbentuk lurus, panjang, dan padat menyerupai lidi mie tebal disebut...", jawaban: "Spaghetti", poin: 20 },
    { soal: "Makanan pokok pengganti nasi bertekstur lengket seperti lem dari sagu yang biasa dimakan dengan kuah kuning pedas di Maluku dan Papua adalah...", jawaban: "Papeda", poin: 30 },
    { soal: "Rempah biji berwarna hitam kelam khas Nusantara yang menjadi penyedap rahasia dan pemberi warna pekat pada kuah Rawon adalah...", jawaban: "Kluwek", poin: 40 },
    { soal: "Jajanan lengket manis berbentuk lonjong khas Garut dan daerah lain yang pembuatannya harus diaduk di wajan besar seharian adalah...", jawaban: "Dodol", poin: 20 },
    { soal: "Minuman seduhan teh dicampur susu kental manis khas Melayu yang dituang tinggi-tinggi antar gelas hingga berbusa tebal disebut Teh...", jawaban: "Tarik", poin: 20 },
    { soal: "Jajanan khas jalanan Amerika berupa sosis bakar yang dijepit belahan roti memanjang dengan saus mustard disebut...", jawaban: "Hot dog", poin: 20 },
    { soal: "Kue basah tradisional berbalur kelapa parut yang saat digigit akan memuncratkan isian gula merah cair dari dalamnya adalah kue...", jawaban: "Klepon", poin: 20 },
    { soal: "Tradisi menyajikan aneka dedaunan dan sayur mentah segar khas tanah Sunda sebagai teman makan sambal terasi disebut...", jawaban: "Lalapan", poin: 20 },
    { soal: "Soto berkuah kaldu susu atau santan khas Jakarta dengan isian kentang goreng, tomat, dan emping disebut Soto...", jawaban: "Betawi", poin: 30 },
    { soal: "Saus kental cair perpaduan gula aren, bawang putih, dan cabai yang rasanya asam manis pedas sebagai cocolan pempek Palembang disebut...", jawaban: "Cuko", poin: 30 },
    { soal: "Minuman dingin meriah yang isinya meliputi potongan nangka, alpukat, kolang-kaling, kelapa muda, dan susu kental manis sering disebut Es...", jawaban: "Campur", poin: 10 },
    { soal: "Jajanan gurih kulit lumpia khas ibukota Jawa Tengah yang isian utamanya adalah tumisan rebung bambu beraroma khas dinamakan...", jawaban: "Lumpia Semarang", poin: 30 },
    { soal: "Sajian lauk basah berkuah santan kental berbumbu rempah pekat khas rumah makan Padang (misal isi otak sapi atau ayam) umumnya disebut...", jawaban: "Gulai", poin: 30 },
    { soal: "Bumbu penyedap berbentuk cair kental berwarna hitam yang membedakan sate Madura dengan sate Taichan adalah...", jawaban: "Kecap manis", poin: 10 },
    { soal: "Sajian ikan berkuah kuning pucat keasaman tanpa santan khas Maluku dan Sulawesi Utara yang sangat segar dinamakan Ikan Kuah...", jawaban: "Asam", poin: 40 }, // Atau Ikan Kuah Kuning
    { soal: "Cemilan kerupuk renyah kulit sapi kering khas dari daerah Garut dan sekitarnya sering disebut...", jawaban: "Dorokdok", poin: 50 },

    // --- Pop Culture, Film, Artis & Tren ---
    { soal: "Franchise film fiksi ilmiah perang luar angkasa yang sangat ikonik dengan senjata pedang laser 'Lightsaber' berjudul...", jawaban: "Star Wars", poin: 30 },
    { soal: "Penyanyi solo wanita muda Indonesia jebolan pencarian bakat yang mempopulerkan lagu galau 'Sisa Rasa' dan 'Melawan Restu' adalah...", jawaban: "Mahalini", poin: 30 },
    { soal: "Boygroup K-Pop asal Korea di bawah naungan agensi SM Entertainment yang memiliki banyak sub-unit seperti Dream, U, dan 127 adalah...", jawaban: "NCT", poin: 40 },
    { soal: "Platform media sosial berbagi video durasi pendek dengan sistem algoritma For You Page (FYP) yang sangat viral saat ini adalah...", jawaban: "TikTok", poin: 10 },
    { soal: "Aktor bela diri pencak silat Indonesia yang tenar lewat film 'The Raid' dan bermain di sekuel film Hollywood 'John Wick 3' adalah...", jawaban: "Iko Uwais", poin: 30 },
    { soal: "Karakter detektif fiksi jenius asal London ciptaan penulis Sir Arthur Conan Doyle yang tinggal di alamat 221B Baker Street adalah...", jawaban: "Sherlock Holmes", poin: 40 },
    { soal: "Serial film animasi klasik asal Amerika tentang keluarga unik berkulit kuning yang nama bapaknya adalah Homer berjudul...", jawaban: "The Simpsons", poin: 30 },
    { soal: "Karakter superhero alien dari planet Krypton di komik DC yang menyamar jadi wartawan bernama Clark Kent adalah...", jawaban: "Superman", poin: 20 },
    { soal: "Grup musik Rock & Roll legendaris dari Inggris tahun 60-an yang anggotanya terdiri dari John, Paul, George, dan Ringo adalah...", jawaban: "The Beatles", poin: 40 },
    { soal: "Dalam anime dan manga Naruto, sebutan untuk kepala desa ninja Konoha yang merupakan cita-cita sang tokoh utama adalah...", jawaban: "Hokage", poin: 20 },
    { soal: "Merek mobil bertenaga listrik canggih yang diproduksi secara massal oleh perusahaan milik miliarder Elon Musk bernama...", jawaban: "Tesla", poin: 20 },
    { soal: "Ajang olahraga gulat bebas dan seni bela diri campuran (MMA) terbesar di dunia yang menggunakan kurungan segi delapan disingkat...", jawaban: "UFC", poin: 40 },
    { soal: "Pemain sepak bola asal Argentina yang memegang rekor peraih trofi individu Ballon d'Or terbanyak sepanjang masa (hingga tahun 2024) adalah...", jawaban: "Lionel Messi", poin: 20 },
    { soal: "Karakter villain utama berkulit ungu di film Marvel Avengers yang misinya mengumpulkan 6 Infinity Stones bernama...", jawaban: "Thanos", poin: 20 },
    { soal: "Platform situs berbagi video terbesar sedunia yang dibeli dan kini dimiliki oleh perusahaan raksasa Google adalah...", jawaban: "YouTube", poin: 10 },
    { soal: "Nama lain yang lebih populer untuk menyebut ajang penghargaan film paling bergengsi 'Academy Awards' di Amerika Serikat adalah piala...", jawaban: "Oscar", poin: 30 },
    { soal: "Tokoh kartun beruang gemuk penyuka madu bertubuh kuning yang selalu memakai baju merah tanpa celana adalah...", jawaban: "Winnie the Pooh", poin: 20 },
    { soal: "Rubrik permainan mengasah otak mencari kata berdasarkan petunjuk menurun dan mendatar di koran sering disingkat...", jawaban: "TTS", poin: 10 }, // Teka Teki Silang
    { soal: "Grup musik indie komedi parodi asal kota Bandung yang digawangi oleh seniman nyentrik Pidi Baiq (penulis Dilan) bernama The...", jawaban: "Panasdalam", poin: 60 },
    { soal: "Sapaan wajib di grup keluarga WhatsApp pada pagi hari yang biasanya dikirim oleh para orang tua sambil melampirkan gambar bunga editan adalah ucapan...", jawaban: "Selamat Pagi", poin: 10 }
];

module.exports = bankSoal;