const kumpulanQuotes = [
    // --- Motivasi & Kesuksesan ---
    "Kegagalan adalah bumbu yang memberi rasa pada kesuksesan. - Truman Capote",
    "Jangan menunggu waktu yang tepat, ciptakan waktu yang tepat. - George Bernard Shaw",
    "Pendidikan adalah senjata paling mematikan di dunia, karena dengan pendidikan, Anda dapat mengubah dunia. - Nelson Mandela",
    "Hiduplah seolah engkau mati besok. Belajarlah seolah engkau hidup selamanya. - Mahatma Gandhi",
    "Orang yang tak pernah membuat kesalahan adalah orang yang tidak pernah mencoba hal baru. - Albert Einstein",
    "Sukses berjalan dari satu kegagalan ke kegagalan yang lain, tanpa kehilangan antusiasme. - Winston Churchill",
    "Apa yang kita pikirkan menentukan apa yang akan terjadi pada kita. - Norman Vincent Peale",
    "Tidak ada rahasia untuk sukses. Sukses adalah hasil dari persiapan, kerja keras, dan belajar dari kegagalan. - Colin Powell",
    "Bermimpilah setinggi langit. Jika engkau jatuh, engkau akan jatuh di antara bintang-bintang. - Soekarno",
    "Cara memulai adalah dengan berhenti berbicara dan mulai melakukan. - Walt Disney",
    "Satu-satunya cara untuk melakukan pekerjaan hebat adalah dengan mencintai apa yang Anda lakukan. - Steve Jobs",
    "Kesuksesan bukanlah akhir, kegagalan bukanlah hal yang fatal: keberanian untuk melanjutkan itulah yang penting. - Winston Churchill",
    "Jangan takut untuk melepaskan yang baik demi yang hebat. - John D. Rockefeller",
    "Sebuah perjalanan ribuan mil dimulai dengan satu langkah. - Lao Tzu",
    "Kualitas bukanlah sebuah tindakan, melainkan sebuah kebiasaan. - Aristoteles",
    "Waktumu terbatas, jadi jangan sia-siakan dengan menjalani hidup orang lain. - Steve Jobs",
    "Risiko terbesar adalah tidak mengambil risiko apa pun. - Mark Zuckerberg",
    "Bukan gunung di hadapan Anda yang menahan Anda, melainkan kerikil di sepatu Anda. - Muhammad Ali",
    "Kelemahan terbesar kita terletak pada menyerah. Cara paling pasti untuk sukses adalah selalu mencoba satu kali lagi. - Thomas A. Edison",
    "Jangan biarkan apa yang tidak bisa Anda lakukan mengganggu apa yang bisa Anda lakukan. - John Wooden",

    // --- Ilmu Pengetahuan & Pendidikan ---
    "Ilmu itu seperti air. Jika ia tidak bergerak, ia akan menjadi keruh lalu membusuk. - Imam Syafi'i",
    "Barangsiapa belum pernah merasakan pahitnya menuntut ilmu walau sesaat, ia akan menelan hinanya kebodohan sepanjang hidupnya. - Imam Syafi'i",
    "Tujuan pendidikan itu untuk mempertajam kecerdasan, memperkukuh kemauan serta memperhalus perasaan. - Tan Malaka",
    "Pendidikan bukanlah proses mengisi wadah yang kosong, pendidikan adalah proses menyalakan api pikiran. - W.B. Yeats",
    "Jika kamu tidak tahan terhadap lelahnya belajar, maka kamu akan menanggung bahayanya kebodohan. - Imam Syafi'i",
    "Ilmu tanpa amal adalah gila, dan amal tanpa ilmu adalah kesia-siaan. - Imam Ghazali",
    "Buku adalah jendela dunia, dan membaca adalah kuncinya.",
    "Investasi dalam pengetahuan selalu membayar bunga terbaik. - Benjamin Franklin",
    "Akar dari pendidikan itu pahit, tapi buahnya manis. - Aristoteles",
    "Belajar tanpa berpikir itu tidak berguna, tapi berpikir tanpa belajar itu sangatlah berbahaya. - Kong Hu Cu",
    "Seorang terpelajar harus juga belajar membaca yang tersirat, bukan hanya yang tersurat. - Pramoedya Ananta Toer",
    "Orang bijak belajar ketika mereka bisa. Orang bodoh belajar ketika mereka terpaksa. - Arthur Wellesley",
    "Pendidikan adalah paspor untuk masa depan, karena hari esok adalah milik mereka yang mempersiapkannya hari ini. - Malcolm X",
    "Pengetahuan yang benar bukan diukur dari seberapa banyak yang kau ingat, melainkan seberapa banyak yang kau amalkan.",
    "Guru yang biasa-biasa saja memberitahu. Guru yang baik menjelaskan. Guru yang ulung mendemonstrasikan. Guru yang hebat menginspirasi. - William Arthur Ward",

    // --- Kebijaksanaan Islami & Spiritual ---
    "Jangan bersedih, sesungguhnya Allah bersama kita. (QS. At-Taubah: 40)",
    "Kesabaran itu ada dua macam: sabar atas sesuatu yang tidak kau ingin dan sabar menahan diri dari sesuatu yang kau ingini. - Ali bin Abi Thalib",
    "Orang yang paling aku sukai adalah dia yang menunjukkan kesalahanku. - Umar bin Khattab",
    "Lidahmu jangan kau biarkan menyebut kekurangan orang lain, sebab kau pun punya kekurangan dan orang lain pun punya lidah. - Imam Syafi'i",
    "Mengetahui sesuatu dan tidak melakukannya sama dengan tidak mengetahuinya. - Imam Ghazali",
    "Apa yang melewatkanku tidak akan pernah menjadi takdirku, dan apa yang ditakdirkan untukku tidak akan pernah melewatkanku. - Umar bin Khattab",
    "Berilah cinta tanpa meminta balasan, dan kita akan menemukan cinta yang jauh lebih indah. - Jalaluddin Rumi",
    "Jangan menjelaskan tentang dirimu kepada siapapun, karena yang menyukaimu tidak butuh itu, dan yang membencimu tidak percaya itu. - Ali bin Abi Thalib",
    "Ciri kelalaian manusia adalah sering mengeluh ketika diuji dan jarang bersyukur ketika diberi nikmat.",
    "Hati menjadi resah dan gelisah ketika kita terbiasa berandai-andai dalam menyikapi persoalan hidup. - Aa Gym",
    "Air mata berasa asin karena air mata adalah garam kehidupan. - Buya Hamka",
    "Balas dendam terbaik adalah menjadikan dirimu lebih baik. - Ali bin Abi Thalib",
    "Perkataan sahabat yang jujur lebih besar harganya daripada harta benda yang diwarisi dari nenek moyang. - Ali bin Abi Thalib",
    "Kekayaan yang paling kekal adalah akal, dan kemiskinan yang paling besar adalah kebodohan. - Ali bin Abi Thalib",
    "Bukanlah kesabaran jika masih mempunyai batas, dan bukanlah keikhlasan jika masih merasakan sakit.",
    "Boleh jadi kamu membenci sesuatu, padahal ia amat baik bagimu. (QS. Al-Baqarah: 216)",
    "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. (QS. Al-Baqarah: 286)",
    "Jika Allah bersamamu, maka siapa yang bisa melawanmu? Dan jika Allah menentangmu, maka siapa yang bisa menolongmu?",
    "Kemuliaan seseorang ada pada agamanya, kehormatannya pada akalnya, dan muru'ahnya pada akhlaknya. - Umar bin Khattab",
    "Orang yang kuat bukanlah orang yang jago bergulat, melainkan orang yang mampu menahan amarahnya.",

    // --- Nasihat Kehidupan & Karakter ---
    "Lebih baik diasingkan daripada menyerah pada kemunafikan. - Soe Hok Gie",
    "Kejujuran adalah perhiasan jiwa yang lebih bersinar daripada berlian.",
    "Orang yang pesimis melihat kesulitan di setiap kesempatan. Orang yang optimis melihat kesempatan di setiap kesulitan. - Winston Churchill",
    "Berbuat baiklah tanpa perlu alasan.",
    "Kadang-kadang, pilihan terbaik adalah menerima keadaan, bersyukur, dan terus melangkah.",
    "Jangan membandingkan dirimu dengan siapa pun di dunia ini. Jika kamu melakukannya, kamu menghina dirimu sendiri. - Bill Gates",
    "Tidak ada bantal yang lebih lembut daripada hati nurani yang bersih. - Peribahasa Prancis",
    "Kebahagiaan bukan bergantung pada siapa dirimu atau apa yang kamu miliki, tapi sepenuhnya bergantung pada apa yang kamu pikirkan. - Dale Carnegie",
    "Hidup itu sederhana, kita saja yang membuatnya sulit. - Confucius",
    "Waktu adalah pedang. Jika kau tidak memotongnya, ia yang akan memotongmu.",
    "Ketakutan akan penderitaan lebih buruk daripada penderitaan itu sendiri. - Paulo Coelho",
    "Berhenti berharap keadaan menjadi lebih mudah. Berharaplah kamu menjadi lebih baik. - Jim Rohn",
    "Karakter seperti pohon dan reputasi seperti bayangannya. Bayangan adalah apa yang kita pikirkan tentangnya; pohon adalah hal yang nyata. - Abraham Lincoln",
    "Sopan santun adalah hal kecil yang membuat perbedaan besar.",
    "Orang besar berbicara tentang ide, orang biasa berbicara tentang kejadian, dan orang kecil berbicara tentang orang lain. - Eleanor Roosevelt",

    // --- Kepemimpinan & Keberanian ---
    "Pemimpin yang baik tahu jalan, melewati jalan tersebut, dan menunjukkan jalan itu kepada orang lain. - John C. Maxwell",
    "Keberanian tidak selalu mengaum. Kadang-kadang keberanian adalah suara kecil di penghujung hari yang mengatakan 'Saya akan mencoba lagi besok'. - Mary Anne Radmacher",
    "Seorang pemimpin adalah pembagi harapan. - Napoleon Bonaparte",
    "Contoh bukanlah cara utama dalam memengaruhi orang lain. Ia adalah satu-satunya cara. - Albert Schweitzer",
    "Untuk bisa memimpin sebuah orkestra, Anda harus membelakangi kerumunan. - Max Lucado",
    "Berani menegakkan keadilan, walaupun mengenai dirimu sendiri. - Buya Hamka",
    "Jangan tanyakan apa yang negara dapat lakukan untuk Anda, tanyakan apa yang dapat Anda lakukan untuk negara. - John F. Kennedy",
    "Jika tindakan-tindakan Anda menginspirasi orang lain untuk bermimpi lebih, belajar lebih, melakukan lebih, dan menjadi lebih, Anda adalah seorang pemimpin. - John Quincy Adams",
    "Kekuatan tidak datang dari kapasitas fisik. Ia datang dari kemauan yang tak terhingga. - Mahatma Gandhi",
    "Keberanian adalah perlawanan terhadap rasa takut, penguasaan rasa takut, bukan ketiadaan rasa takut. - Mark Twain",

    // --- Keberagaman & Kebangsaan (Lokal) ---
    "Bangsa yang besar adalah bangsa yang menghormati jasa pahlawannya. - Soekarno",
    "Jatuh bangunnya negara ini, sangat tergantung dari bangsa ini sendiri. Makin pudar persatuan dan kepedulian, Indonesia hanyalah sekadar nama dan gambar seuntaian pulau di peta. - Mohammad Hatta",
    "Terkadang, kesulitan harus kamu rasakan terlebih dulu sebelum kebahagiaan yang sempurna datang kepadamu. - R.A. Kartini",
    "Gila hormat adalah penyakit jiwa yang paling berbahaya. - Gus Dur",
    "Tidak penting apa pun agama atau sukumu, kalau kamu bisa melakukan sesuatu yang baik untuk semua orang, orang tidak pernah tanya apa agamu. - Gus Dur",
    "Tuhan tidak perlu dibela, Dia sudah maha segalanya. Belalah mereka yang diperlakukan tidak adil. - Gus Dur",
    "Kemerdekaan hanyalah didapat dan dimiliki oleh bangsa yang jiwanya berkobar-kobar dengan tekad ‘Merdeka, merdeka atau mati’! - Soekarno",
    "Kurang cerdas dapat diperbaiki dengan belajar, kurang cakap dapat dihilangkan dengan pengalaman. Namun tidak jujur itu sulit diperbaiki. - Mohammad Hatta",
    "Banyak hal yang bisa menjatuhkanmu. Tapi satu-satunya hal yang benar-benar dapat menjatuhkanmu adalah sikapmu sendiri. - R.A. Kartini",
    "Dalam menghadapi musuh, tak ada yang lebih mengena daripada senjata kasih sayang. - Cut Nyak Dien",
    
    // --- Penutup (Sikap Harian) ---
    "Hari ini adalah hari pertama untuk sisa hidupmu.",
    "Tersenyumlah, karena senyum adalah sedekah.",
    "Minta maaflah ketika salah, berterima kasihlah ketika dibantu, dan tolonglah saat ada yang kesusahan.",
    "Jangan lupa bernapas dan menyadari bahwa kamu masih diberi kesempatan hari ini.",
    "Bukan seberapa cepat kamu berlari, tapi seberapa jauh kamu mampu bertahan.",
    "Masa depan bermula dari doa dan usaha di pagi hari.",
    "Jaga lisan, jaga pikiran, jaga tindakan.",
    "Setiap tetes keringat perjuangan akan menjadi saksi di masa depan.",
    "Jadilah seperti padi, kian berisi kian merunduk.",
    "Semua akan indah pada waktunya, selama kita tidak berhenti berusaha.",

    "Ilmu itu didapat dengan lisan yang gemar bertanya dan akal yang suka berpikir. - Abdullah bin Abbas",
    "Siapa yang menempuh jalan untuk mencari ilmu, maka Allah akan mudahkan baginya jalan menuju surga. - HR. Muslim",
    "Adab itu seperti akar sebuah pohon, sedangkan ilmu adalah buahnya. Tanpa akar, pohon takkan berbuah.",
    "Waktu di kala belajar adalah kawah candradimuka. Bersakit-sakit dahulu, bermanfaat kemudian.",
    "Jangan meremehkan kebaikan sekecil apapun, meski hanya senyuman saudaramu. - HR. Muslim",
    "Sebaik-baik manusia adalah yang paling bermanfaat bagi manusia lainnya. - HR. Ahmad",
    "Bukanlah anak yatim itu yang ditinggal mati orang tuanya, tapi anak yatim sejati adalah yatim ilmu dan adab. - Ali bin Abi Thalib",
    "Menghafal butuh ketekunan, memahami butuh kejernihan hati, mengamalkan butuh keikhlasan.",
    "Jadikanlah sabar dan shalat sebagai penolongmu. - QS. Al-Baqarah: 45",
    "Doa tanpa usaha adalah kebohongan, usaha tanpa doa adalah kesombongan.",
    "Niatkan setiap lelahmu lillahi ta'ala, maka ia takkan pernah sia-sia.",
    "Membaca bukan hanya memfasihkan lisan, tapi melunakkan hati yang keras.",
    "Ulama adalah pewaris para nabi, dan jalan menuju ke sana dimulai dari bangku madrasah.",
    "Jika kamu tidak bisa berlomba dengan orang shalih dalam ibadahnya, berlombalah dengan para pendosa dalam istighfarnya. - Ibnu Rajab",
    "Seseorang akan senantiasa menjadi orang berilmu selama ia terus belajar. Jika ia merasa sudah pintar, maka saat itulah ia menjadi bodoh. - Hasan Al-Bashri",
    "Jaga ingatanmu dengan menjauhi maksiat, karena ilmu adalah cahaya, dan cahaya Allah tidak diberikan kepada pelaku maksiat. - Imam Waki'",
    "Tidurnya orang yang berilmu lebih baik daripada ibadahnya orang yang bodoh.",
    "Berkahlah sebuah ilmu ketika guru ridho kepada muridnya.",
    "Cinta dunia adalah sumber segala kesalahan. - HR. Baihaqi",
    "Tidak ada kebaikan dalam ibadah yang tak ada ilmunya, dan tak ada kebaikan dalam ilmu yang tak dipahami. - Ali bin Abi Thalib",
    "Tinggalkanlah sesuatu yang meragukanmu dan beralihlah pada apa yang tidak meragukanmu. - HR. Tirmidzi",
    "Orang yang hebat bukanlah yang bisa menaklukkan dunia, tapi yang bisa menundukkan hawa nafsunya sendiri.",
    "Bersyukurlah atas apa yang ada, maka Allah akan menambahkan apa yang belum ada.",
    "Setiap kebaikan yang kau pelajari akan menjadi saksi yang meringankan langkahmu di akhirat.",
    "Lidah yang selalu berdzikir adalah perisai dari hati yang gundah.",

    // --- Bisnis, Usaha & Manajemen ---
    "Modal utama dalam membangun usaha bukanlah uang, melainkan kepercayaan dan relasi.",
    "Jangan berniaga hanya untuk mencari untung, tapi berniagalah untuk memberikan solusi bagi orang lain.",
    "Konsumen yang paling tidak puas adalah sumber pelajaran paling berharga bagi sistemmu. - Bill Gates",
    "Sebuah usaha keluarga yang sukses dibangun di atas fondasi komunikasi yang jujur dan pembagian peran yang adil.",
    "Membangun usaha itu seperti menanam pohon. Butuh waktu untuk menyirami sebelum bisa memetik buahnya.",
    "Jangan letakkan semua telurmu dalam satu keranjang. - Warren Buffett",
    "Kegagalan hari ini adalah uang sekolah untuk kesuksesanmu esok hari.",
    "Inovasi membedakan antara seorang pemimpin dan pengikut. - Steve Jobs",
    "Harga adalah apa yang Anda bayar, nilai adalah apa yang Anda dapatkan. - Warren Buffett",
    "Manajemen keuangan yang tidak jelas ibarat berlayar tanpa kompas.",
    "Rezeki sudah diatur, tapi jumlahnya tergantung seberapa cerdas dan keras kita menjemputnya.",
    "Pedagang yang jujur dan dapat dipercaya akan bersama para nabi, shiddiqin, dan syuhada. - HR. Tirmidzi",
    "Peluang tidak terjadi begitu saja, Anda yang menciptakannya. - Chris Grosser",
    "Sukses bukan tentang ide yang brilian, tapi tentang eksekusi yang konsisten.",
    "Waktu Anda adalah modal terbesar Anda, jangan buang untuk hal yang tidak menghasilkan nilai tambah.",
    "Jangan takut dengan kompetitor, takutlah pada pelayananmu yang mulai menurun.",
    "Karyawan dan tim yang bahagia akan merawat pelangganmu dengan baik.",
    "Uang bisa membeli banyak hal, tapi reputasi yang baik tidak bisa dibeli dengan uang.",
    "Berani mengambil risiko besar berarti bersiap menerima hadiah yang besar pula.",
    "Disiplin dalam mengatur hal-hal kecil akan membuatmu tangguh mengelola hal besar.",
    "Sebuah merek bukanlah nama, melainkan janji yang ditepati kepada publik.",
    "Jatuh 9 kali, bangkit 10 kali. Itulah mental pantang menyerah sejati.",
    "Bekerjalah dalam diam, biarkan kesuksesanmu yang membuat keributan.",
    "Membantu orang lain menyelesaikan masalah mereka adalah esensi sejati keberhasilan.",
    "Visi tanpa eksekusi hanyalah sebuah halusinasi.",

    // --- Teknologi, Logika & Inovasi ---
    "Kode program yang baik adalah kodenya sendiri yang menjadi dokumentasi terbaiknya.",
    "Sistem itu sangat polos, ia hanya melakukan persis apa yang kamu perintahkan, bukan apa yang kamu inginkan.",
    "Jangan menyelesaikan sebuah masalah dengan membuat masalah baru. Pahami dulu akar logikanya.",
    "Sistem yang hebat tidak dibangun dalam semalam, ia adalah hasil dari ribuan perbaikan kecil secara bertahap.",
    "Teknologi hanyalah alat. Pada akhirnya, yang terpenting adalah bagaimana ia mempermudah hidup manusia.",
    "Kesalahan sintaks adalah cara mesin mengajarimu tentang ketelitian.",
    "Keamanan sebuah jaringan sama kuatnya dengan mata rantai terlemahnya.",
    "Jangan pernah mengetik saat kamu sedang lelah, atau kamu akan menghabiskan dua hari untuk memperbaiki kesalahan dua menit.",
    "Ada dua cara menulis program bebas masalah: cara pertama tidak ada, cara kedua juga tidak ada. - Alan Perlis",
    "Seorang pengembang sejati tidak pernah berhenti belajar, karena teknologi tidak pernah berhenti berkembang.",
    "Sebelum kamu mulai mengerjakan sesuatu, pastikan kamu sudah benar-benar memahami alur logikanya.",
    "Internet of Things (IoT) mengubah benda mati menjadi alat yang cerdas dan penurut.",
    "Otomatisasi tidak merampas pekerjaan manusia, ia membebaskan manusia dari tugas yang membosankan.",
    "Pembuat sistem yang baik tahu apa yang harus ditulis. Pembuat sistem yang hebat tahu apa yang harus dihapus.",
    "Jika sesuatu bekerja tapi kamu tidak tahu kenapa, itu bukan kesuksesan, itu kebetulan semata.",
    "Optimasi yang terlalu cepat adalah akar dari banyak kerumitan di kemudian hari.",
    "Menyimpan data cadangan (backup) adalah 'ibadah wajib' di dunia digital.",
    "Jangan salahkan server jika fondasinya yang berantakan.",
    "Desain antarmuka (UI) ibarat lelucon. Kalau kamu harus menjelaskannya agar orang paham, berarti itu tidak bagus.",
    "Pesan error adalah sahabat terbaik seorang pemecah masalah. Jangan diabaikan.",
    "Bekerja sama dengan mesin membutuhkan satu bahasa utama: logika murni.",
    "Jangan repot-repot membuat ulang roda. Gunakan sumber daya yang ada, fokuslah pada pemecahan masalah utamanya.",
    "Kecepatan dan efisiensi jauh lebih penting daripada tampilan yang cantik tapi berat untuk dijalankan.",
    "Sebuah karya belum selesai jika belum diuji oleh pengguna aslinya.",
    "Memecahkan masalah bukan sekadar soal seberapa cepat, tapi soal efisiensi alur berpikir.",

    // --- Kepemimpinan, Komunikasi & Kata Bijak Umum ---
    "Kata-kata yang diucapkan tulus dari hati akan sampai langsung ke hati pendengarnya.",
    "Pemimpin sejati tidak menciptakan pengikut, ia menciptakan pemimpin baru.",
    "Berbicara di depan umum bukan tentang seberapa hebat bahasamu, tapi seberapa jujur pesanmu.",
    "Saat kau ragu melangkah, ambillah napas panjang, dan majulah satu langkah saja.",
    "Jangan menasehati orang saat ia sedang marah, ibarat menasihati api dengan menuangkan minyak.",
    "Kedewasaan tidak diukur dari usia, melainkan dari cara kita merespons masalah secara tenang.",
    "Berdamailah dengan masa lalu agar ia tidak merusak masa depanmu yang sedang dibangun.",
    "Rasa hormat tidak bisa diminta secara paksa, ia harus dipantaskan untuk didapatkan.",
    "Jangan jadikan kesibukan pekerjaan sebagai alasan untuk melupakan keluarga di rumah.",
    "Menyalahkan orang lain adalah jalan pintas para pengecut untuk menghindari tanggung jawab.",
    "Orang yang paling bijak adalah yang tahu kapan waktu yang tepat untuk bicara dan kapan harus diam.",
    "Jangan berjanji saat sangat bahagia, jangan membalas saat sangat marah, jangan memutuskan saat sedang sedih.",
    "Masa-masa sulit selalu berhasil mengungkapkan siapa sahabat sejatimu yang sebenarnya.",
    "Kegelisahan hari ini tidak akan mengubah esok hari, ia hanya merampas kebahagiaan hari ini.",
    "Jadilah pendengar yang baik, karena setiap orang selalu punya cerita yang ingin didengar.",
    "Kejujuran mungkin tidak membuatmu punya banyak teman, tapi ia akan menyeleksi dan memberimu teman yang tepat.",
    "Menangis bukanlah tanda kelemahan. Sejak lahir, menangis adalah tanda pertama bahwa kita hidup.",
    "Tak perlu repot menjelaskan siapa dirimu, waktu dan perbuatanmu yang akan membuktikan segalanya.",
    "Jika kamu ingin pergi cepat, pergilah sendiri. Jika kamu ingin pergi jauh, pergilah bersama-sama dengan tim.",
    "Cintai orang yang mengkritikmu, karena dari merekalah kau menemukan letak kesalahanmu.",
    "Orang yang tidak pernah bersyukur dengan hal kecil, tidak akan pernah merasa cukup meski diberi hal besar.",
    "Perjalanan sejauh seribu mil selalu dimulai dengan memastikan sepatumu terikat dengan benar.",
    "Jangan terlalu keras pada dirimu sendiri. Bahkan bulan pun harus melewati fase gelap untuk kembali bercahaya penuh.",
    "Jadilah seperti pohon yang lebat buahnya; dilempar dengan batu, dibalas dengan menjatuhkan buah yang manis.",
    "Kebaikan yang kau tanam perlahan hari ini, pasti akan mekar menjadi senyuman di esok hari."
];

module.exports = kumpulanQuotes;